# Generated by Django 5.0.14 on 2026-09-15 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '9062_lead_source_salon'),
        ('finance', '9028_transaction_date_localdate'),
        ('warehouse', '0023_alter_warehousepayrollentry_op_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client_key', models.CharField(blank=True, default='', help_text='Ключ форми: повторне натискання «Зберегти» не створює друге повернення', max_length=64)),
                ('reason', models.CharField(choices=[('color', 'Не підійшов колір'), ('damaged', 'Пошкоджено'), ('wh_error', 'Помилка складу'), ('mgr_error', 'Помилка менеджера'), ('changed_mind', 'Передумав')], max_length=16, verbose_name='Причина')),
                ('delivery_payer', models.CharField(choices=[('client', 'Клієнт'), ('us', 'Ми')], default='client', max_length=8, verbose_name='Хто платить доставку повернення')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Доставка повернення, ₴')),
                ('comment', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='На скільки зменшилась сума угоди')),
                ('cost_back', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Собівартість товару, що повернувся на склад')),
                ('cost_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Собівартість браку / списаного')),
                ('stock_note', models.CharField(blank=True, default='', max_length=255)),
                ('money_status', models.CharField(choices=[('none', 'Повертати нічого'), ('pending', 'Очікує рішення бухгалтера'), ('refund', 'Гроші повернуто клієнту'), ('liqpay', 'Повернуто через LiqPay'), ('offset', 'Зараховано в наступне замовлення')], db_index=True, default='none', max_length=8)),
                ('money_due', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Скільки треба вирішити бухгалтеру')),
                ('money_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Повернуто / зараховано')),
                ('money_at', models.DateTimeField(blank=True, null=True)),
                ('money_comment', models.CharField(blank=True, default='', max_length=255)),
                ('contact', models.ForeignKey(blank=True, help_text='Клієнт угоди на момент повернення', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='crm.deal')),
                ('error', models.ForeignKey(blank=True, help_text='«Помилка співробітника» (причина — помилка складу / менеджера)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warehouse.warehouseerror')),
                ('manager', models.ForeignKey(blank=True, help_text='Відповідальний за угоду на момент повернення (для звіту)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('money_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receipt_doc', models.ForeignKey(blank=True, help_text='Прибуткова накладна товару «як новий»', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warehouse.stockdocument')),
                ('refund_tx', models.OneToOneField(blank=True, help_text='Операція «Повернення коштів» у журналі', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_return', to='finance.transaction')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DealReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_item_id', models.IntegerField(blank=True, help_text='Позиція угоди (при повному поверненні позицію видалено)', null=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=16)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sold_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Було в позиції до повернення', max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='На скільки зменшилась сума позиції')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Собівартість одиниці (знімок позиції)')),
                ('destination', models.CharField(choices=[('stock', 'На склад як новий'), ('defect', 'В брак'), ('writeoff', 'Списати')], default='stock', max_length=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warehouse.product')),
                ('ret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='returns.dealreturn')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DealReturnPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='warehouse_photos/returns/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='returns.dealreturn')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dealreturn',
            constraint=models.UniqueConstraint(condition=models.Q(('client_key', ''), _negated=True), fields=('client_key',), name='uniq_dealreturn_client_key'),
        ),
    ]
