# Generated by Django 5.0.14 on 2026-09-14 14:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '9061_lead_quality'),
        ('telephony', '0010_callqueueconfig_ring_ext_callqueueconfig_ring_ext_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissedCallSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start', models.TimeField(default=datetime.time(9, 0), help_text='Початок робочого дня (для 15 робочих хвилин)')),
                ('work_end', models.TimeField(default=datetime.time(18, 0), help_text='Кінець робочого дня')),
                ('work_days', models.JSONField(blank=True, default=list, help_text='Робочі дні 0=Пн…6=Нд; порожньо = щодня')),
                ('sla_minutes', models.PositiveIntegerField(default=15, help_text='За скільки робочих хвилин треба передзвонити')),
                ('escalate_minutes', models.PositiveIntegerField(default=60, help_text='Через скільки робочих хвилин сказати керівнику')),
                ('escalate_user_ids', models.JSONField(blank=True, default=list, help_text='Кому ескалація; порожньо = власник (суперадмін)')),
                ('auto_task', models.BooleanField(default=True, help_text='Ставити задачу «Передзвонити» відповідальному')),
                ('ignore_numbers', models.JSONField(blank=True, default=list, help_text='Номери, які НЕ потрапляють у чергу (внутрішні)')),
                ('ignore_staff_numbers', models.BooleanField(default=True, help_text='Не рахувати дзвінки з номерів співробітників')),
                ('active_since', models.DateTimeField(blank=True, help_text='З цього моменту пропущені йдуть у чергу', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налаштування пропущених',
            },
        ),
        migrations.CreateModel(
            name='MissedCallItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone9', models.CharField(db_index=True, help_text='Останні 9 цифр номера клієнта', max_length=12)),
                ('number', models.CharField(blank=True, max_length=32)),
                ('line', models.CharField(blank=True, max_length=60)),
                ('line_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('call_ids', models.JSONField(blank=True, default=list)),
                ('calls_count', models.PositiveIntegerField(default=1)),
                ('first_missed_at', models.DateTimeField(db_index=True)),
                ('last_missed_at', models.DateTimeField()),
                ('assign_reason', models.CharField(blank=True, choices=[('owner', 'Власник клієнта'), ('last_manager', 'Останній менеджер клієнта'), ('on_duty', 'Черговий на зміні'), ('transfer', 'Передано колегою')], max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('first_attempt_at', models.DateTimeField(blank=True, help_text='Перший вихідний на номер після пропуску', null=True)),
                ('reaction_work_min', models.IntegerField(blank=True, help_text='Реакція, робочих хвилин', null=True)),
                ('status', models.CharField(choices=[('open', 'Треба передзвонити'), ('closed', 'Оброблено')], db_index=True, default='open', max_length=8)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, choices=[('callback', 'Передзвонили'), ('client_called', 'Клієнт додзвонився сам'), ('other_channel', 'Оброблено іншим каналом'), ('not_relevant', 'Клієнт не актуальний'), ('task_closed', 'Задачу закрили вручну')], max_length=16)),
                ('close_note', models.CharField(blank=True, max_length=300)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('history', models.JSONField(blank=True, default=list)),
                ('backfilled', models.BooleanField(default=False, help_text='Створено з історії (без задачі і сповіщень)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missed_call_items', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('closing_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='telephony.call')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.deal')),
                ('first_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='telephony.call')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.task')),
            ],
            options={
                'ordering': ['-first_missed_at', '-id'],
                'indexes': [models.Index(fields=['status', 'assignee'], name='missed_status_assignee')],
            },
        ),
    ]
