# Generated by Django 5.0.14 on 2026-09-24 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('kind', models.CharField(choices=[('business', 'Особистий чат (Telegram Business)'), ('group', 'Робоча група'), ('import', 'Імпорт історії')], default='business', max_length=12)),
                ('enabled', models.BooleanField(default=True, help_text='Вимкнений чат не зберігається й не аналізується')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_enabled', models.BooleanField(default=False, help_text='Щоночі розбирати нові повідомлення (платно)')),
                ('model', models.CharField(default='claude-sonnet-4-6', max_length=40)),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('owner_tg_id', models.BigIntegerField(blank=True, help_text='Telegram id Олега — щоб знати, що сказав він', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('from_owner', models.BooleanField(default=False, help_text='Написав/сказав сам Олег')),
                ('author', models.CharField(blank=True, max_length=160)),
                ('sender_id', models.BigIntegerField(blank=True, db_index=True, help_text='Telegram id відправника', null=True)),
                ('kind', models.CharField(choices=[('text', 'Текст'), ('voice', 'Голосове'), ('video_note', 'Кружечок'), ('photo', 'Фото'), ('document', 'Файл'), ('other', 'Інше')], default='text', max_length=12)),
                ('text', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True, help_text='Розшифровка голосового')),
                ('file_id', models.CharField(blank=True, max_length=255)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(db_index=True)),
                ('transcribed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, help_text='Коли ШІ вже розібрав', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantchat')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fact', 'Факт / знання'), ('price', 'Ціна / умови постачальника'), ('agreement', 'Домовленість'), ('decision', 'Рішення'), ('style', 'Мій стиль / як я кажу')], db_index=True, default='fact', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('who', models.CharField(blank=True, help_text='З ким / про кого', max_length=160)),
                ('due', models.DateField(blank=True, help_text='Строк домовленості', null=True)),
                ('evidence', models.JSONField(blank=True, default=list, help_text='[{message_id, quote}] — звідки взято')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('accepted', 'Додано'), ('rejected', 'Відхилено')], db_index=True, default='new', max_length=10)),
                ('knowledge_item_id', models.IntegerField(blank=True, help_text='Чернетка в базі знань після «Додати»', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assistant.assistantchat')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='assistantmessage',
            constraint=models.UniqueConstraint(fields=('chat', 'message_id'), name='assistant_msg_chat_mid_uniq'),
        ),
    ]
