# Generated by Django 5.0.14 on 2026-08-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtAccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers_count', models.IntegerField(default=0)),
                ('total_likes', models.BigIntegerField(default=0)),
                ('videos_count', models.IntegerField(default=0)),
                ('audience_ages', models.JSONField(blank=True, default=list)),
                ('audience_genders', models.JSONField(blank=True, default=list)),
                ('audience_countries', models.JSONField(blank=True, default=list)),
                ('audience_cities', models.JSONField(blank=True, default=list)),
                ('audience_activity', models.JSONField(blank=True, default=list)),
                ('averages', models.JSONField(blank=True, default=dict)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TtDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('followers_total', models.IntegerField(default=0)),
                ('followers_gained', models.IntegerField(default=0)),
                ('followers_lost', models.IntegerField(default=0)),
                ('profile_views', models.IntegerField(default=0)),
                ('video_views', models.IntegerField(default=0)),
                ('unique_video_views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('bio_link_clicks', models.IntegerField(default=0)),
                ('email_clicks', models.IntegerField(default=0)),
                ('phone_clicks', models.IntegerField(default=0)),
                ('address_clicks', models.IntegerField(default=0)),
                ('lead_submissions', models.IntegerField(default=0)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TtVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('caption', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('thumbnail_url', models.TextField(blank=True, default='')),
                ('share_url', models.TextField(blank=True, default='')),
                ('duration', models.FloatField(default=0.0)),
                ('views', models.BigIntegerField(default=0)),
                ('reach', models.BigIntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('average_time_watched', models.FloatField(default=0.0)),
                ('full_video_watched_rate', models.FloatField(default=0.0)),
                ('total_time_watched', models.FloatField(default=0.0)),
                ('impression_sources', models.JSONField(blank=True, default=list)),
                ('audience_countries', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
