# Generated by Django 5.0.14 on 2026-06-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_conversation_participants'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
    ]
