# Generated by Django 5.0.14 on 2026-06-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_alter_conversation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='internal',
            field=models.BooleanField(default=False, help_text='Внутрішня нотатка — видно лише менеджерам, клієнту НЕ йде'),
        ),
    ]
