# Generated by Django 5.0.14 on 2026-06-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_conversation_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Надіслано'), ('delivered', 'Доставлено'), ('failed', 'Не доставлено'), ('window_risk', 'Вікно закрите — міг не дійти')], default='sent', help_text='Статус доставки вихідного', max_length=12),
        ),
    ]
