# Generated by Django 5.0.14 on 2026-07-01 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0009_teammessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('conversation', 'external_id'), name='uniq_conv_extid'),
        ),
    ]
