# Generated by Django 5.0.14 on 2026-07-06 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0011_soundlibrary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammessage',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='NULL = загальний чат (усім)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
