# Generated by Django 5.0.14 on 2026-09-23 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0023_quickreply_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerHoldSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Увімкнено')),
                ('delay_sec', models.PositiveIntegerField(default=90, help_text='Якщо менеджер за цей час сам написав клієнту — нічого не надсилаємо', verbose_name='Пауза після «взяв чат», сек')),
                ('take_window_sec', models.PositiveIntegerField(default=900, verbose_name='Вікно після «взяв чат», сек')),
                ('wait_minutes', models.PositiveIntegerField(default=15, help_text='Чат уже закріплений, клієнт написав і чекає довше цього часу — теж пишемо один раз', verbose_name='Клієнт чекає, хв')),
                ('per_dialog_hours', models.PositiveIntegerField(default=24, verbose_name='Не частіше ніж раз на, год')),
                ('promise_minutes', models.PositiveIntegerField(default=30, verbose_name='Обіцяємо відповідь протягом, хв')),
                ('work_from', models.TimeField(default=datetime.time(9, 0), verbose_name='Пишемо з')),
                ('work_to', models.TimeField(default=datetime.time(20, 0), verbose_name='Пишемо до')),
                ('text_take', models.TextField(default='Вітаю! Мене звати {менеджер} 😊 Вже дивлюсь ваш запит — повернусь із відповіддю до {час}.', verbose_name='Текст, коли менеджер узяв чат')),
                ('text_waiting', models.TextField(default='Я з вашим запитом, {менеджер} на звʼязку 😊 Збираю для вас точну інформацію — відповім до {час}.', verbose_name='Текст, коли клієнт чекає')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
