# Generated by Django 5.0.14 on 2026-09-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0024_managerholdsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerholdsettings',
            name='max_wait_hours',
            field=models.PositiveIntegerField(default=2, help_text='Захист від масової розсилки по старих діалогах: пишемо лише поки очікування свіже', verbose_name='Не пишемо, якщо клієнт чекає довше, год'),
        ),
    ]
