# Generated by Django 5.0.14 on 2026-09-24 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('telegram', 'Telegram')], max_length=16)),
                ('handle', models.CharField(help_text='Імʼя сторінки без @, у нижньому регістрі (для YouTube channel/ID)', max_length=150)),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('own', 'Наша сторінка'), ('competitor', 'Конкурент'), ('inspiration', 'Натхнення')], default='competitor', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Вимкнена сторінка не аналізується, але історія лишається')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'platform', 'handle'],
            },
        ),
        migrations.AddConstraint(
            model_name='contentchannel',
            constraint=models.UniqueConstraint(fields=('platform', 'handle'), name='cf_channel_platform_handle_uniq'),
        ),
    ]
