# Generated by Django 5.0.14 on 2026-09-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('model', models.CharField(choices=[('claude-sonnet-4-6', 'Sonnet 4.6 — точніше групує'), ('claude-haiku-4-5', 'Haiku 4.5 — найдешевше')], default='claude-sonnet-4-6', max_length=40)),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=2, help_text='Ліміт на місяць. Досягнуто — розбір зупиняється до 1-го числа', max_digits=6)),
                ('min_new', models.PositiveSmallIntegerField(default=5, help_text='Менше нових питань — ШІ не викликаємо')),
                ('backfill_days', models.PositiveSmallIntegerField(default=7, help_text='Перший запуск бере питання за стільки днів')),
                ('last_message_id', models.BigIntegerField(default=0, help_text='До якого повідомлення вже розібрано')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_note', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Питання словами клієнта, українською', max_length=200)),
                ('material', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('new', 'Нова'), ('planned', 'У плані контенту'), ('done', 'Контент зроблено'), ('ignored', 'Не для контенту')], db_index=True, default='new', max_length=12)),
                ('examples', models.JSONField(blank=True, default=list, help_text='До 5 останніх формулювань, без телефонів і пошти')),
                ('kb_item_id', models.IntegerField(blank=True, help_text='Схожий затверджений запис бази знань (пошук за словами)', null=True)),
                ('kb_item_title', models.CharField(blank=True, max_length=200)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='QuestionMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(help_text='inbox.Message.id (без FK — історію не чіпаємо)', unique=True)),
                ('channel', models.CharField(blank=True, max_length=24)),
                ('asked_at', models.DateTimeField(db_index=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='content_factory.questiontopic')),
            ],
        ),
    ]
