# Generated by Django 5.0.14 on 2026-09-24 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0002_questionsettings_questiontopic_questionmention'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_drafts', models.BooleanField(default=False, help_text='Щоранку чернетка з найчастішого питання (платно, в межах ліміту)')),
                ('model', models.CharField(choices=[('claude-sonnet-4-6', 'Sonnet 4.6 — точніше групує'), ('claude-haiku-4-5', 'Haiku 4.5 — найдешевше')], default='claude-sonnet-4-6', max_length=40)),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=2, max_digits=6)),
                ('channel', models.CharField(default='@wallcovpro', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TgPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('material', models.CharField(blank=True, max_length=80)),
                ('photo_ids', models.JSONField(blank=True, default=list, help_text='inbox.MediaLibraryItem — лише реальні фото обʼєктів')),
                ('facts', models.JSONField(blank=True, default=list, help_text='Назви записів бази знань, з яких узято факти')),
                ('checks', models.JSONField(blank=True, default=list, help_text='Що перевірити людині перед публікацією')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('approved', 'Схвалено'), ('rejected', 'Відхилено'), ('published', 'Опубліковано')], db_index=True, default='draft', max_length=12)),
                ('model', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tg_message_id', models.CharField(blank=True, max_length=40)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_posts', to='content_factory.questiontopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
