# Generated by Django 5.0.14 on 2026-09-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0003_tgsettings_tgpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgpost',
            name='publish_error',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tgpost',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Коли опублікувати (лише схвалені). Порожньо — вручну', null=True),
        ),
        migrations.AddField(
            model_name='tgpost',
            name='video_ids',
            field=models.JSONField(blank=True, default=list, help_text='inbox.MediaLibraryItem kind=video (24.09, публікація)'),
        ),
    ]
