# Generated by Django 5.0.14 on 2026-09-24 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0004_tgpost_publish_error_tgpost_scheduled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('kind', models.CharField(blank=True, help_text='group / supergroup / channel', max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tgpost',
            name='source_ids',
            field=models.JSONField(blank=True, default=list, help_text='SourceAsset з TG — шлються за file_id, без завантаження'),
        ),
        migrations.CreateModel(
            name='SourceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('telegram', 'Telegram'), ('drive', 'Google Drive')], default='telegram', max_length=12)),
                ('kind', models.CharField(choices=[('photo', 'Фото'), ('video', 'Відео'), ('document', 'Файл'), ('audio', 'Аудіо')], max_length=12)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('media_group_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('file_id', models.CharField(help_text='Telegram file_id або Drive fileId', max_length=255)),
                ('file_unique_id', models.CharField(max_length=128, unique=True)),
                ('thumb_file_id', models.CharField(blank=True, max_length=255)),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True, help_text='Підпис під файлом — з нього беремо теги')),
                ('link', models.URLField(blank=True, max_length=500)),
                ('material', models.CharField(blank=True, db_index=True, max_length=80)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('hidden', models.BooleanField(default=False, help_text='Не показувати в добірках (сміття, дубль)')),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='content_factory.sourcechat')),
            ],
            options={
                'ordering': ['-posted_at', '-id'],
            },
        ),
    ]
