# Generated by Django 5.0.14 on 2026-09-24 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0005_sourcechat_tgpost_source_ids_sourceasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('files_count', models.IntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tgpost',
            name='reactions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tgpost',
            name='reactions_detail',
            field=models.JSONField(blank=True, default=dict, help_text='{емодзі: кількість}'),
        ),
        migrations.AddField(
            model_name='tgpost',
            name='stats_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tgpost',
            name='views',
            field=models.IntegerField(blank=True, help_text='Перегляди з публічного віджета каналу', null=True),
        ),
        migrations.CreateModel(
            name='TgPostStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(blank=True, null=True)),
                ('reactions', models.IntegerField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='content_factory.tgpost')),
            ],
            options={
                'ordering': ['taken_at'],
            },
        ),
    ]
