# Generated by Django 5.0.14 on 2026-09-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0006_drivefolder_tgpost_reactions_tgpost_reactions_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period_days', models.PositiveSmallIntegerField(default=7)),
                ('summary', models.TextField(help_text='Звіт простими словами')),
                ('ideas', models.JSONField(blank=True, default=list, help_text='[{title, hook, why, format, material}]')),
                ('inputs', models.JSONField(blank=True, default=dict, help_text='Цифри, на яких зроблено звіт')),
                ('model', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalystSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_enabled', models.BooleanField(default=False, help_text='Щопонеділка звіт (платно, в межах ліміту)')),
                ('model', models.CharField(choices=[('claude-sonnet-4-6', 'Sonnet 4.6 — точніше групує'), ('claude-haiku-4-5', 'Haiku 4.5 — найдешевше')], default='claude-sonnet-4-6', max_length=40)),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('last_feed_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_feed_note', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('platform', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('preview_url', models.URLField(blank=True, max_length=500)),
                ('caption', models.TextField(blank=True)),
                ('media_type', models.CharField(blank=True, max_length=20)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('views', models.BigIntegerField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('engagement', models.FloatField(blank=True, null=True)),
                ('viral_score', models.FloatField(blank=True, null=True)),
                ('is_own', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'Нове'), ('saved', 'В ідеях'), ('used', 'Зроблено з наших'), ('hidden', 'Сховано')], db_index=True, default='new', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
