# Generated by Django 5.0.14 on 2026-09-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0007_analystreport_analystsettings_feeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='preview_url',
            field=models.URLField(blank=True, help_text='Підписані посилання Virale бувають довгими', max_length=2000),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
