# Generated by Django 5.0.14 on 2026-09-24 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0008_alter_feeditem_preview_url_alter_feeditem_url'),
        ('inbox', '0025_managerholdsettings_max_wait_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceasset',
            name='markup_at',
            field=models.DateTimeField(blank=True, help_text='Коли ШІ розмітив сцени (лише відео)', null=True),
        ),
        migrations.CreateModel(
            name='ReelDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('material', models.CharField(blank=True, max_length=80)),
                ('caption', models.TextField(blank=True, help_text='Підпис до рилса')),
                ('beats', models.JSONField(blank=True, default=list, help_text='[{text, scene_id, seconds}] — сценарій по кадрах')),
                ('facts', models.JSONField(blank=True, default=list)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='draft', max_length=12)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.sharedlink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('shot', models.CharField(blank=True, help_text='крупно / загальний план / процес / результат / людина', max_length=40)),
                ('what', models.CharField(max_length=300)),
                ('quality', models.PositiveSmallIntegerField(default=3, help_text='1–5: різкість, світло, чи видно фактуру')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='content_factory.sourceasset')),
            ],
            options={
                'ordering': ['asset_id', 'start'],
            },
        ),
    ]
