# Generated by Django 5.0.14 on 2026-09-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0009_sourceasset_markup_at_reeldraft_videoscene'),
        ('inbox', '0025_managerholdsettings_max_wait_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoscene',
            name='thumb',
            field=models.ForeignKey(blank=True, help_text='Кадр із середини сцени (240px) — для вибору при заміні', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.sharedlink'),
        ),
    ]
