# Generated by Django 5.0.14 on 2026-09-24 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0010_videoscene_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('origin', models.CharField(choices=[('preset', 'Пресет'), ('reference', 'З референсу'), ('blog', 'Наш блог')], default='preset', max_length=12)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('font', models.CharField(default='DejaVu Sans', max_length=40)),
                ('weight', models.CharField(default='Bold', max_length=20)),
                ('size', models.PositiveSmallIntegerField(default=68, help_text='px при ширині 1080')),
                ('color', models.CharField(default='#FFFFFF', max_length=9)),
                ('stroke_color', models.CharField(default='#000000', max_length=9)),
                ('stroke', models.PositiveSmallIntegerField(default=0)),
                ('box', models.BooleanField(default=True)),
                ('box_color', models.CharField(default='#000000', max_length=9)),
                ('box_opacity', models.FloatField(default=0.45)),
                ('position', models.FloatField(default=0.7, help_text='Вертикаль центру тексту: 0 — верх, 1 — низ')),
                ('upper', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('structure', models.JSONField(blank=True, default=dict, help_text='Темп і будова ролика-референсу (якщо було відео)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['origin', 'name'],
            },
        ),
        migrations.AddField(
            model_name='reeldraft',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content_factory.reelstyle'),
        ),
    ]
