# Generated by Django 5.0.14 on 2026-09-25 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0011_reelstyle_reeldraft_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('kind', models.CharField(choices=[('brand', 'Бренд'), ('personal', 'Особистий'), ('hiring', 'Найм'), ('fun', 'Розважальний'), ('other', 'Інше')], default='other', max_length=12)),
                ('about', models.CharField(blank=True, help_text='Одним рядком: про що блог', max_length=300)),
                ('master_prompt', models.TextField(blank=True, help_text='Тема, аудиторія, тон, формати, заборони, заклик — усе, що ШІ має знати')),
                ('goal', models.TextField(blank=True, help_text='Мета блогу (заявки, підписники, найм…) — під неї ШІ радить ефекти й кадри')),
                ('cta', models.TextField(blank=True, help_text='Заклик у кінці підпису/останнього слайда')),
                ('use_crm_kb', models.BooleanField(default=False, help_text='Брати факти ще й з бази знань CRM (AI ЦЕНТР) — для Wallcov')),
                ('label_ai', models.BooleanField(default=False, help_text='Позначати ШІ-кадри «ШІ-візуалізація» (правило Wallcov)')),
                ('real_footage', models.BooleanField(default=False, help_text='Є власні нарізки відео (рилси з наших кадрів)')),
                ('color', models.CharField(default='#e3b85f', max_length=9)),
                ('is_default', models.BooleanField(default=False)),
                ('sort', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.AddField(
            model_name='reeldraft',
            name='busy',
            field=models.BooleanField(default=False, help_text='Йде ШІ-обробка кадру / перемонтаж'),
        ),
        migrations.AddField(
            model_name='contentchannel',
            name='blog',
            field=models.ForeignKey(blank=True, help_text='Для наших сторінок — до якого блогу належить акаунт', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='content_factory.blog'),
        ),
        migrations.AddField(
            model_name='reeldraft',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='content_factory.blog'),
        ),
        migrations.CreateModel(
            name='BlogFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fact', 'Факт'), ('rule', 'Правило'), ('example', 'Приклад'), ('ban', 'Заборона')], default='fact', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='content_factory.blog')),
            ],
            options={
                'ordering': ['kind', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('template', models.CharField(default='photo', max_length=20)),
                ('slides', models.JSONField(blank=True, default=list, help_text='[{headline, body, image:{kind: library|ai|none, link_id, prompt}, rendered_id}]')),
                ('facts', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='draft', max_length=12)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('busy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousels', to='content_factory.blog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
