# Generated by Django 5.0.14 on 2026-09-25 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0012_blogs_carousels'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='funnel',
            field=models.CharField(default='save', help_text='Ціль каруселі: save|share|comment|dm|follow', max_length=12),
        ),
        migrations.AddField(
            model_name='carousel',
            name='kind',
            field=models.CharField(default='single', help_text='single — одна тема по кроках; list — добірка з анонсом', max_length=12),
        ),
        migrations.CreateModel(
            name='ContentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reel', 'Рилс'), ('carousel', 'Карусель'), ('post', 'Пост')], max_length=10)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('promise', models.CharField(blank=True, help_text='Що пообіцяли показати/розповісти далі', max_length=300)),
                ('promise_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.ForeignKey(blank=True, help_text='На яку обіцянку відповідає цей контент', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_by', to='content_factory.contentmemory')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='content_factory.blog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
