# Generated by Django 5.0.14 on 2026-09-25 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0013_carousel_kind_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentchannel',
            name='in_virale',
            field=models.BooleanField(default=False, help_text='Сторінка відстежується у Virale — її ролики йдуть у стрічку'),
        ),
        migrations.AlterField(
            model_name='contentchannel',
            name='blog',
            field=models.ForeignKey(blank=True, help_text='До якого блогу належить сторінка (наша, конкурент чи натхнення)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='content_factory.blog'),
        ),
    ]
