# Generated by Django 5.0.14 on 2026-09-25 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0014_channel_in_virale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_id', models.IntegerField(help_text='inbox.MediaLibraryItem.id (без FK — бібліотеку не чіпаємо)', unique=True)),
                ('score', models.FloatField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('scored_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='analystreport',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='content_factory.blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='ref_images',
            field=models.JSONField(blank=True, default=list, help_text='[{id: SharedLink, who}] — кадри-референси для ШІ-художника'),
        ),
        migrations.AddField(
            model_name='blog',
            name='visual',
            field=models.JSONField(blank=True, default=dict, help_text='Візуальна біблія з прикладу: стиль, персонажі, оточення, рух, темп'),
        ),
        migrations.AddField(
            model_name='drivefolder',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_folders', to='content_factory.blog'),
        ),
        migrations.AddField(
            model_name='sourceasset',
            name='blog',
            field=models.ForeignKey(blank=True, help_text='Блог джерела (з чату чи папки)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='content_factory.blog'),
        ),
        migrations.AddField(
            model_name='sourcechat',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_chats', to='content_factory.blog'),
        ),
    ]
