# Generated by Django 5.0.14 on 2026-09-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0015_blog_scope_visual'),
    ]

    operations = [
        migrations.AddField(
            model_name='reeldraft',
            name='variants',
            field=models.JSONField(blank=True, default=dict, help_text='{tiktok|youtube: SharedLink id} — версії з безпечними зонами платформ'),
        ),
    ]
