# Generated by Django 5.0.14 on 2026-09-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0016_reel_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='reeldraft',
            name='brief',
            field=models.JSONField(blank=True, default=dict, help_text='Задум: title, hook, goal, why, shots, fit, source, structure референсу'),
        ),
        migrations.AddField(
            model_name='reeldraft',
            name='review',
            field=models.JSONField(blank=True, default=dict, help_text='Висновки перевірки командою (SMM, монтажер, бренд)'),
        ),
        migrations.AddField(
            model_name='reeldraft',
            name='stage',
            field=models.CharField(default='done', help_text='Крок майстра: idea/script/material/style/draft/review/done', max_length=10),
        ),
    ]
