# Generated by Django 5.0.14 on 2026-09-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0017_reel_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='published',
            field=models.JSONField(blank=True, default=dict, help_text='{instagram: {id, permalink, at}} — публікація з CRM'),
        ),
        migrations.AddField(
            model_name='reeldraft',
            name='published',
            field=models.JSONField(blank=True, default=dict, help_text='{instagram: {id, permalink, at}, tiktok: {share_id, at}} — публікації з CRM'),
        ),
    ]
