# Generated by Django 5.0.14 on 2026-09-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0019_agentchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentchannel',
            name='api',
            field=models.JSONField(blank=True, default=dict, help_text='27.09: токени офіційного API (TikTok for Business) власного акаунта блогу'),
        ),
    ]
