# Generated by Django 5.0.14 on 2026-09-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0020_channel_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Як пишеться (без урахування регістру)', max_length=80, unique=True)),
                ('spoken', models.CharField(help_text='Як має звучати: з наголосом (кра́ю) або фонетично', max_length=160)),
                ('note', models.CharField(blank=True, help_text='Звідки правило: виправлення власника', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
    ]
