# Generated by Django 5.0.14 on 2026-10-02 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0021_voiceword'),
        ('warehouse', '0032_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('goal', models.CharField(max_length=500)),
                ('audience', models.CharField(max_length=300)),
                ('offer', models.CharField(blank=True, max_length=500)),
                ('product_snapshot', models.JSONField(default=dict)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('budget_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content_factory.blog')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_on', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('approved_hash', models.CharField(blank=True, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_checks', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('carousel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content_factory.carousel')),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content_factory.tgpost')),
                ('reel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content_factory.reeldraft')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='content_factory.contentcampaign')),
            ],
            options={
                'ordering': ['planned_on', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='campaignmaterial',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('carousel__isnull', True), ('post__isnull', True), ('reel__isnull', False)), models.Q(('carousel__isnull', False), ('post__isnull', True), ('reel__isnull', True)), models.Q(('carousel__isnull', True), ('post__isnull', False), ('reel__isnull', True)), _connector='OR'), name='cf_campaign_material_one_target'),
        ),
    ]
