# Generated by Django 5.0.14 on 2026-06-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="funnels",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="crm.funnel"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.role",
            ),
        ),
    ]
