# Generated by Django 5.0.14 on 2026-06-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extension',
            field=models.CharField(blank=True, help_text='внутрішній номер у АТС, напр. 789', max_length=16),
        ),
    ]
