# Generated by Django 5.0.14 on 2026-06-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_stage_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text='Права отдела (коды), действуют на всех членов'),
        ),
        migrations.AlterField(
            model_name='department',
            name='stage_lock',
            field=models.JSONField(blank=True, default=list, help_text='ID стадій, куди ЗАБОРОНЕНО ручне переміщення'),
        ),
        migrations.AlterField(
            model_name='department',
            name='stage_view_all',
            field=models.JSONField(blank=True, default=list, help_text='ID стадій, де бачать ВСІ картки'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='denied_permissions',
            field=models.JSONField(blank=True, default=list, help_text='Персонально запрещённые (приоритет над всем)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='extra_permissions',
            field=models.JSONField(blank=True, default=list, help_text='Персонально выданные права'),
        ),
    ]
