# Generated by Django 5.0.14 on 2026-07-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_department_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='fin_accounts',
            field=models.JSONField(blank=True, default=list, help_text='id рахунків; порожньо = всі'),
        ),
        migrations.AddField(
            model_name='department',
            name='fin_cats_in',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='department',
            name='fin_cats_out',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='department',
            name='fin_counterparties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='department',
            name='fin_dirs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='role',
            name='fin_accounts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='role',
            name='fin_cats_in',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='role',
            name='fin_cats_out',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='role',
            name='fin_counterparties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='role',
            name='fin_dirs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='fin_accounts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='fin_cats_in',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='fin_cats_out',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='fin_counterparties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='fin_dirs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
