# Generated by Django 5.0.14 on 2026-07-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_department_fin_accounts_department_fin_cats_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dismissed_at',
            field=models.DateField(blank=True, help_text='Дата звільнення (для розрахунку скільки пропрацював)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Активний'), ('inactive', 'Неактивний (тимчасово — відпустка/пауза, без доступу)'), ('dismissed', 'Звільнений')], db_index=True, default='active', help_text='Активний / Неактивний / Звільнений. Керує доступом (is_active) і фільтрами аналітики.', max_length=12),
        ),
    ]
