# Generated by Django 5.0.14 on 2026-07-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_dismissed_at_user_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='idle_timeout_min',
            field=models.IntegerField(default=15, help_text='Хвилин простою (без активності) до авто-паузи зміни. 0 = контроль простою вимкнено (напр. Склад/Тонування — працюють руками).'),
        ),
    ]
