# Generated by Django 5.0.14 on 2026-07-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_department_idle_timeout_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, default='', help_text='Коротко про співробітника'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, help_text='День народження', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True, default='', help_text='Інтереси, хобі (щоб краще знати команду)'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.TextField(blank=True, default='', help_text='Фото/лого — data URL (стиснене до 256px у браузері)'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, default='', help_text='Посада (вільний текст, напр. «Старший менеджер»)', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, default='', help_text='Telegram (@nick)', max_length=64),
        ),
    ]
