# Generated by Django 5.0.14 on 2026-07-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_account_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idle_timeout_min',
            field=models.IntegerField(blank=True, help_text='Особистий поріг простою (хв). Порожньо = як у відділі; 0 = вимкнути для цього співробітника.', null=True),
        ),
    ]
