# Generated by Django 5.0.14 on 2026-09-21 20:09

import apps.content_library.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '9066_reorder'),
        ('inbox', '0023_quickreply_products'),
        ('warehouse', '0028_reorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_touch_at', models.DateTimeField(auto_now_add=True)),
                ('last_touch_at', models.DateTimeField(auto_now=True)),
                ('first_touch', models.JSONField(default=dict)),
                ('last_touch', models.JSONField(default=dict)),
                ('preferred_channel', models.CharField(blank=True, max_length=24)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='new', max_length=24)),
                ('tags', models.JSONField(default=list)),
                ('unsubscribe_token', models.CharField(default=apps.content_library.models.token, max_length=64, unique=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_audience', to='crm.contact')),
            ],
        ),
        migrations.CreateModel(
            name='AudienceIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=16)),
                ('value', models.CharField(max_length=254)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='content_library.audienceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField()),
                ('text_version', models.CharField(default='wallcov-materials-20260921', max_length=40)),
                ('source', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_library.audienceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('article_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Опубліковано')], default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('content', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, to='warehouse.product')),
            ],
        ),
        migrations.CreateModel(
            name='GuideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=80, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('token', models.CharField(default=apps.content_library.models.token, max_length=64, unique=True)),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='content_library.audienceprofile')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content_library.instruction')),
            ],
        ),
        migrations.CreateModel(
            name='InstructionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.content_library.models.token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inbox.conversation')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content_library.instruction')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inbox.message')),
            ],
        ),
        migrations.CreateModel(
            name='InstructionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content_library.instruction')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_library.audienceprofile')),
                ('share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_library.instructionshare')),
            ],
        ),
        migrations.AddConstraint(
            model_name='audienceidentity',
            constraint=models.UniqueConstraint(fields=('kind', 'value'), name='unique_content_identity'),
        ),
    ]
