# Generated by Django 5.0.14 on 2026-09-14 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '9061_lead_quality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.CharField(blank=True, default='', max_length=40)),
                ('act_date', models.DateField()),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Внесено'), ('closed', 'Закрито (підтверджено)')], default='draft', max_length=8)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('commission_pct_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payroll_period', models.CharField(blank=True, default='', max_length=7)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='object_acts', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_acts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-act_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='Посада: «Менеджер з продажу», «Комірник», «SMM»…', max_length=120)),
                ('department', models.CharField(blank=True, default='', help_text='Продажі / Склад / Маркетинг / Офіс', max_length=60)),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('purpose', models.CharField(choices=[('official', 'По ній платимо'), ('legacy', 'Як платили раніше (для порівняння)')], default='official', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Діє'), ('draft', 'Чернетка'), ('archived', 'Архів')], default='active', max_length=10)),
                ('employment', models.CharField(choices=[('labor', 'Трудовий договір'), ('fop', 'ФОП'), ('none', 'Без оформлення')], default='none', help_text='Від оформлення залежить, скільки людина коштує компанії (податки)', max_length=6)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, help_text='Включно; порожньо — діє зараз', null=True)),
                ('is_vacancy', models.BooleanField(default=False)),
                ('in_plan', models.BooleanField(default=True, help_text='Враховувати в точці беззбитковості (для вакансії — «що якщо»)')),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, default=dict, help_text='{"insurance_first_month": true}')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payroll.payscheme')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pay_schemes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department', 'position', '-valid_from', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayRateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=24)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log', to='payroll.payscheme')),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('base_by_days', 'За вихід / ставка (по табелю)'), ('fixed_monthly', 'Фіксовано на місяць'), ('standard', 'Стандарт роботи (премія до …)'), ('margin_share', '% з маржі продажів'), ('revenue_share', '% з обороту / суми акту'), ('event_bonus', 'Бонус «тест-набір → основне»'), ('guarantee', 'Гарантія новачку'), ('piece_rate', 'Відрядно (склад)')], max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.payscheme')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
