# Generated by Django 5.0.14 on 2026-09-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('platform', models.CharField(blank=True, default='', max_length=16)),
                ('reason', models.CharField(blank=True, choices=[('ads_data', 'Подія з даними реклами'), ('phrase_no_referral', 'Текст кнопки з реклами, але Meta не дала referral')], default='', max_length=24)),
                ('sender_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ad_id', models.CharField(blank=True, default='', max_length=64)),
                ('phrase', models.CharField(blank=True, default='', max_length=120)),
                ('event', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Сирий вебхук Meta (реклама, 30 днів)',
                'ordering': ['-id'],
            },
        ),
    ]
