# Generated by Django 5.0.14 on 2026-09-14 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0022_product_consumption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.IntegerField(db_index=True)),
                ('day', models.DateField(db_index=True)),
                ('lint_findings', models.IntegerField(default=0)),
                ('ai_findings', models.IntegerField(default=0)),
                ('items_created', models.IntegerField(default=0)),
                ('model', models.CharField(blank=True, default='', max_length=40)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_enabled', models.BooleanField(default=False, help_text='Щоденний рецензент закритих чатів (Claude)')),
                ('reviewer_model', models.CharField(default='claude-haiku-4-5', max_length=40)),
                ('reviewer_sample', models.PositiveIntegerField(default=20, help_text='Скільки закритих чатів за день перевіряти')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('create', 'Створено'), ('import', 'Імпортовано'), ('edit', 'Змінено'), ('propose', 'Запропоновано правку'), ('approve', 'Затверджено'), ('archive', 'В архів'), ('restore', 'Повернуто в чернетки'), ('publish', 'Опубліковано в ChatPlace')], max_length=10)),
                ('snapshot', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rule', 'Правило'), ('fact', 'Факт'), ('qa', 'Питання-відповідь'), ('template', 'Шаблон')], db_index=True, default='qa', max_length=12, verbose_name='Тип')),
                ('topic', models.CharField(choices=[('payment', 'Оплата'), ('delivery', 'Доставка'), ('test_sets', 'Тест-набори'), ('pricing', 'Ціни і прорахунок'), ('materials', 'Матеріали'), ('application', 'Нанесення та інструмент'), ('tinting', 'Тонування і кольори'), ('contacts', 'Контакти'), ('discounts', 'Знижки та акції'), ('objections', 'Заперечення'), ('company', 'Про компанію'), ('tone', 'Тон і заборони'), ('process', 'Процеси CRM'), ('other', 'Інше')], db_index=True, default='other', max_length=20, verbose_name='Тема')),
                ('audience', models.JSONField(blank=True, default=list, help_text='Коди агентів з AGENTS: хто отримує цей запис', verbose_name='Для яких агентів')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('approved', 'Затверджено'), ('archived', 'Архів')], db_index=True, default='draft', max_length=10, verbose_name='Статус')),
                ('title', models.CharField(max_length=300, verbose_name='Питання / назва')),
                ('text', models.TextField(help_text='Ціни не писати цифрами — {price:ID товару} або {m2:ID товару}', verbose_name='Текст для агента / відповідь клієнту')),
                ('internal_note', models.TextField(blank=True, default='', verbose_name='Внутрішня примітка')),
                ('source', models.CharField(choices=[('manual', 'Вручну'), ('import_kb', 'Стара база AI ЦЕНТРУ'), ('code', 'Правило з коду CRM'), ('reviewer', 'Рецензент (пропозиція)'), ('chatplace', 'ChatPlace')], db_index=True, default='manual', max_length=12, verbose_name='Джерело')),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', help_text='kbentry:<id> — стара база AI ЦЕНТРУ; code:<ключ>; proposal:<id>', max_length=120, verbose_name='Посилання на джерело')),
                ('external_ids', models.JSONField(blank=True, default=dict, help_text='Ідентифікатори копій: chatplace_ig / chatplace_tt')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Для пропозицій рецензента: діалог, цитата, у чому проблема')),
                ('priority', models.IntegerField(default=100, verbose_name='Пріоритет (менше — вище)')),
                ('popularity', models.IntegerField(default=0, verbose_name='Скільки разів питали клієнти')),
                ('version', models.PositiveIntegerField(default=1)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, help_text='Товари, ціни яких агент бачить разом із записом', related_name='knowledge_items', to='warehouse.product')),
                ('replaces', models.ForeignKey(blank=True, help_text='Пропонована правка до затвердженого запису', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='knowledge.knowledgeitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['topic', 'priority', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgereviewlog',
            constraint=models.UniqueConstraint(fields=('conversation_id', 'day'), name='kn_review_conv_day'),
        ),
        migrations.AddField(
            model_name='knowledgesettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgeversion',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgeversion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.knowledgeitem'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['status', 'topic'], name='kn_item_status_topic'),
        ),
    ]
