# Generated by Django 5.0.14 on 2026-09-14 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgesettings',
            name='webchat_ai_enabled',
            field=models.BooleanField(default=False, help_text='ІІ відповідає у веб-чаті (лише затверджене «Сайт»)'),
        ),
        migrations.AddField(
            model_name='knowledgesettings',
            name='webchat_model',
            field=models.CharField(default='claude-haiku-4-5', max_length=40),
        ),
        migrations.CreateModel(
            name='KnowledgeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('precheck', 'Попередня перевірка чернеток'), ('controller', 'Контролер закритих чатів'), ('publish', 'Публікація в Юлю (ChatPlace)')], db_index=True, max_length=12)),
                ('status', models.CharField(choices=[('running', 'Виконується'), ('done', 'Готово'), ('error', 'Помилка')], db_index=True, default='running', max_length=10)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('total', models.PositiveIntegerField(default=0)),
                ('done', models.PositiveIntegerField(default=0)),
                ('est_cost_usd', models.FloatField(default=0)),
                ('cost_usd', models.FloatField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('backup', models.JSONField(blank=True, default=list, help_text='Публікація: база ChatPlace до запису')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('ready', 'Готово до затвердження'), ('fix', 'Потрібна правка'), ('dup', 'Дубль'), ('conflict', 'Суперечить затвердженому або каталогу CRM')], db_index=True, max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('ref_item_id', models.IntegerField(blank=True, help_text='Дубль / суперечність з записом №', null=True)),
                ('item_version', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(default='ai', help_text='code — перевірка кодом ($0); ai — Claude', max_length=6)),
                ('model', models.CharField(blank=True, default='', max_length=40)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='precheck', to='knowledge.knowledgeitem')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.knowledgerun')),
            ],
        ),
    ]
