# Generated by Django 5.0.14 on 2026-09-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_ai_channel_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgesettings',
            name='ai_max_per_day',
            field=models.PositiveSmallIntegerField(default=15, help_text='Скільки відповідей ШІ може дати в одному чаті за добу'),
        ),
        migrations.AlterField(
            model_name='knowledgesettings',
            name='ai_silence_hours',
            field=models.PositiveSmallIntegerField(default=12, help_text='Скільки годин ШІ мовчить у чаті після повідомлення менеджера'),
        ),
        migrations.AlterField(
            model_name='knowledgesettings',
            name='webchat_ai_enabled',
            field=models.BooleanField(default=False, help_text='ШІ відповідає у веб-чаті (лише затверджене «Сайт»)'),
        ),
    ]
