# Generated by Django 5.0.14 on 2026-09-14 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('marketing', 'Маркетинг / SMM'), ('sales', 'Продажі'), ('warehouse', 'Склад'), ('salon', 'Салон'), ('objects', 'Обʼєкти'), ('content', 'Контент / сайт'), ('ai_crm', 'ІІ і CRM'), ('office', 'Офіс')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True, help_text='Показувати напрям на біржі')),
                ('archived', models.BooleanField(default=False, help_text='Видалено (мʼяко): ніде не показується, історія лишається')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Напрям біржі задач',
                'verbose_name_plural': 'Напрями біржі задач',
                'ordering': ['department', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Ціна на момент «Беру»', max_digits=10)),
                ('unit', models.CharField(default='task', max_length=6)),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Для «% з оплат»: сума оплат, з якої рахуємо відсоток', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('taken', 'Взято в роботу'), ('submitted', 'Здано на перевірку'), ('rework', 'На доробку'), ('accepted', 'Прийнято'), ('cancelled', 'Скасовано')], db_index=True, default='taken', max_length=10)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('proof_text', models.TextField(blank=True, default='')),
                ('proof_url', models.CharField(blank=True, default='', max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Нараховано після «Прийнято»', max_digits=12)),
                ('quality', models.PositiveSmallIntegerField(blank=True, help_text='Оцінка якості 1–5 (для рейтингу)', null=True)),
                ('payroll_period', models.CharField(blank=True, db_index=True, default='', help_text='Місяць ЗП (YYYY-MM), куди йде сума', max_length=7)),
                ('comment', models.TextField(blank=True, default='', help_text='Коментар перевіряючого')),
                ('std_score', models.FloatField(blank=True, help_text='Основний стандарт людини на момент «Беру» (0–1)', null=True)),
                ('std_warning', models.CharField(blank=True, default='', max_length=255)),
                ('history', models.JSONField(blank=True, default=list)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bounty_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Взята задача біржі',
                'verbose_name_plural': 'Взяті задачі біржі',
                'ordering': ['-taken_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('data', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='bounty.taskclaim')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('how_to', models.TextField(blank=True, default='', help_text='Як виконати — кроки, кожен з нового рядка')),
                ('done_criteria', models.TextField(blank=True, default='', help_text='Що вважається виконаним і який доказ')),
                ('proof_type', models.CharField(choices=[('any', 'Посилання, фото або текст'), ('link', 'Посилання'), ('photo', 'Фото / файл'), ('text', 'Текстовий звіт')], default='any', max_length=6)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='₴ за одиницю; для «% з оплат» — відсоток', max_digits=10)),
                ('unit', models.CharField(choices=[('task', 'за задачу'), ('piece', 'за штуку'), ('hour', 'за годину'), ('pct', '% з оплат')], default='task', max_length=6)),
                ('unit_label', models.CharField(blank=True, default='', help_text='Для «за штуку»: що саме — «відео», «контакт», «50 товарів»', max_length=40)),
                ('monthly_limit_qty', models.PositiveIntegerField(default=0, help_text='Скільки одиниць на місяць усього; 0 — без ліміту')),
                ('max_per_person', models.PositiveIntegerField(default=0, help_text='Скільки одиниць на місяць на одну людину; 0 — без ліміту')),
                ('max_takers', models.PositiveSmallIntegerField(default=1, help_text='Скільки людей можуть виконувати одночасно; 1 — «зайнято» для інших; 0 — скільки завгодно')),
                ('due_days', models.PositiveSmallIntegerField(default=3, help_text='Термін виконання після «Беру», днів')),
                ('active', models.BooleanField(default=False, help_text='Видно співробітникам і можна брати')),
                ('archived', models.BooleanField(default=False, help_text='Видалено (мʼяко)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', help_text='Службова примітка: «ціна для обговорення»', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='bounty.taskcategory')),
                ('checker', models.ForeignKey(blank=True, help_text='Хто приймає; порожньо — власник / право «Керувати біржею задач»', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача біржі',
                'verbose_name_plural': 'Задачі біржі',
                'ordering': ['category__department', 'category__order', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='taskclaim',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='bounty.taskoffer'),
        ),
    ]
