# Generated by Django 5.0.14 on 2026-09-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0002_subtasks_expected_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='department',
            field=models.CharField(choices=[('marketing', 'Маркетинг / SMM'), ('sales', 'Продажі'), ('warehouse', 'Склад'), ('salon', 'Офлайн-магазин (салон)'), ('objects', 'Обʼєкти'), ('content', 'Контент / сайт'), ('ai_crm', 'ШІ і CRM'), ('hr', 'Найм'), ('office', 'Офіс')], db_index=True, max_length=16),
        ),
    ]
