# Generated by Django 5.0.14 on 2026-06-28 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9011_dialoganalysis'),
        ('warehouse', '0002_product_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Назва')),
                ('tare_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Вага порожньої тари, кг')),
                ('max_fill_kg', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Вмістимість, кг')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['max_fill_kg'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Вага нетто, кг'),
        ),
        migrations.CreateModel(
            name='WarehouseJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'У черзі'), ('taken', 'Взято'), ('tinting', 'Тонується'), ('packing', 'Пакування'), ('awaiting_photos', 'Потрібні фото'), ('shipped', 'Відвантажено'), ('partial', 'Часткове'), ('cancelled', 'Скасовано')], db_index=True, default='queued', max_length=16)),
                ('is_shipment', models.BooleanField(default=True)),
                ('tinted_kits', models.JSONField(blank=True, default=list)),
                ('tintings_count', models.PositiveIntegerField(default=0)),
                ('tintings_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipped_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('pack_le5_count', models.PositiveIntegerField(default=0)),
                ('pack_le10_count', models.PositiveIntegerField(default=0)),
                ('pack_le20_count', models.PositiveIntegerField(default=0)),
                ('packed', models.BooleanField(default=True, help_text='Чи самі пакували (ні = >4 місць, контейнер НП)')),
                ('np_ttn', models.CharField(blank=True, default='', max_length=40)),
                ('done_snapshot', models.JSONField(blank=True, default=dict)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_jobs', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_jobs', to='crm.deal')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_job', to='crm.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehousePayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('op_type', models.CharField(choices=[('shipment_weight', 'Вага відвантаження'), ('packing', 'Упаковка'), ('tinting', 'Тонування'), ('workday', 'Робочий день'), ('error', 'Помилка'), ('wrong_material', 'Невірний матеріал'), ('bonus_initiative', 'Бонус-ідея'), ('bonus_cleanliness', 'Бонус-чистота')], max_length=20)),
                ('quantity_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('pack_tier', models.CharField(blank=True, default='', max_length=4)),
                ('base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_applied', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='confirmed', max_length=10)),
                ('source', models.CharField(default='system', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.deal')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh_payroll', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll', to='warehouse.warehousejob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehousePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('buckets', 'Відерця'), ('parcel', 'Посилка'), ('cleanliness', 'Чистота'), ('error_proof', 'Доказ помилки')], max_length=16)),
                ('image', models.FileField(upload_to='warehouse_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.deal')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='warehouse.warehousejob')),
            ],
        ),
    ]
