# Generated by Django 5.0.14 on 2026-06-28 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9011_dialoganalysis'),
        ('warehouse', '0003_taretype_product_weight_kg_warehousejob_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Нова'), ('accepted', 'Прийнято'), ('implemented', 'Впроваджено'), ('declined', 'Відхилено')], default='new', max_length=12)),
                ('award_uah', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh_ideas', to=settings.AUTH_USER_MODEL)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual_staff', 'Сам визнав'), ('manager', 'Менеджер/РОП'), ('ai_suggested', 'AI')], default='manual_staff', max_length=16)),
                ('kind', models.CharField(choices=[('wrong_material', 'Невірний матеріал'), ('wrong_tint', 'Невірна тонировка'), ('wrong_qty', 'Невірна кількість'), ('damaged', 'Пошкоджено'), ('lost_np', 'Втрачено в НП'), ('other', 'Інше')], default='other', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('deduction_uah', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('suggested', 'На розгляді'), ('confirmed', 'Підтверджено'), ('rejected', 'Відхилено')], default='suggested', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blamed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wh_errors_blamed', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.deal')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='warehouse.warehousejob')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wh_errors_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
