# Generated by Django 5.0.14 on 2026-07-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_initiativeidea_warehouseerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdocument',
            name='posted',
            field=models.BooleanField(default=True, verbose_name='Проведено'),
        ),
    ]
