# Generated by Django 5.0.14 on 2026-07-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_stockdocument_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdocument',
            name='close_stage',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Стадія закриття'),
        ),
    ]
