# Generated by Django 5.0.14 on 2026-07-03 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_stockdocument_close_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='b24_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='b24_created_by',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Хто створив (Б24)'),
        ),
        migrations.AddField(
            model_name='product',
            name='b24_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='b24_modified_by',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Хто змінив (Б24)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('b24_file_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='warehouse.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
