# Generated by Django 5.0.14 on 2026-07-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_product_b24_created_at_product_b24_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdocument',
            name='kind',
            field=models.CharField(choices=[('in', 'Приход'), ('out', 'Расход'), ('inv', 'Инвентаризация'), ('writeoff', 'Списание')], max_length=8),
        ),
    ]
