# Generated by Django 5.0.14 on 2026-07-03 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_stockdocument_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Кількість')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='warehouse.product')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bundles', to='warehouse.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productcomponent',
            constraint=models.UniqueConstraint(fields=('bundle', 'component'), name='uniq_bundle_component'),
        ),
        migrations.AddConstraint(
            model_name='productcomponent',
            constraint=models.CheckConstraint(check=models.Q(('bundle', models.F('component')), _negated=True), name='bundle_not_self'),
        ),
    ]
