# Generated by Django 5.0.14 on 2026-07-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_productcomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=True, help_text='Вимкни для послуг/робіт/номенклатури без залишку — не списується зі складу, залишок не рахується', verbose_name='Кількісний облік'),
        ),
    ]
