# Generated by Django 5.0.14 on 2026-09-19 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9066_reorder'),
        ('warehouse', '0027_error_kinds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Коли залишок менший — товар сам зʼявляється складу у «Замовити». 0 = не контролюємо', max_digits=12, verbose_name='Мінімальний залишок'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_qty',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Кратність замовлення (відро, мішок, упаковка). 0 = довести до мінімуму ×2', max_digits=12, verbose_name='Замовляти по'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Постачальник для заявок. Порожньо — з останнього приходу цього товару', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='crm.contact'),
        ),
        migrations.CreateModel(
            name='ReorderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lines', models.JSONField(blank=True, default=list)),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('task_ids', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorder_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
