# Generated by Django 5.0.14 on 2026-09-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0030_internal_material_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='density_kg_l',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Скільки кілограмів у 1 літрі (з техлиста, напр. 1,5). Потрібна, щоб порахувати обʼєм і підібрати тару: літри = вага ÷ щільність.', max_digits=6, null=True, verbose_name='Щільність, кг/л'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_drop',
            field=models.BooleanField(default=False, help_text='Товар, який ми продаємо ПІД замовлення і закуповуємо ПІСЛЯ продажу. Коли робиш прихід — закупівельна ціна автоматично оновлюється в УСІХ угодах з цим товаром (навіть у закритих) і в русі товару. Для звичайних складських товарів вимкнено — там історія собівартості на момент продажу не змінюється.', verbose_name='Дроп (докупаємо під замовлення)'),
        ),
        migrations.AlterField(
            model_name='stockdocument',
            name='kind',
            field=models.CharField(choices=[('in', 'Приход'), ('out', 'Расход'), ('inv', 'Инвентаризация'), ('writeoff', 'Списание'), ('repack', 'Розлив/Фасування')], max_length=8),
        ),
    ]
