# Generated by Django 5.0.14 on 2026-10-01 10:50

from django.db import migrations, models


BASE = ["шт", "кг", "г", "л", "мл", "м", "см", "м²", "м³", "пог.м", "рулон", "упаковка",
        "комплект", "набір", "пара", "відро", "банка", "пляшечка", "туба", "мішок",
        "пачка", "лист", "день", "година", "послуга"]
FULL = {"шт": "Штука", "кг": "Кілограм", "г": "Грам", "л": "Літр", "мл": "Мілілітр",
        "м": "Метр", "см": "Сантиметр", "м²": "Квадратний метр", "м³": "Кубічний метр",
        "пог.м": "Погонний метр", "година": "Година", "день": "День", "послуга": "Послуга"}


def seed(apps, schema_editor):
    """Довідник = старий зашитий список + усе, що РЕАЛЬНО стоїть у картках товарів,
    щоб жодна наявна одиниця не зникла з вибору."""
    Unit = apps.get_model("warehouse", "Unit")
    Product = apps.get_model("warehouse", "Product")
    used = set(x for x in Product.objects.values_list("unit", flat=True).distinct() if x and x.strip())
    order = {n: i for i, n in enumerate(BASE)}
    for n in list(BASE) + sorted(used - set(BASE)):
        Unit.objects.get_or_create(name=n, defaults={
            "full_name": FULL.get(n, ""), "sort_order": order.get(n, 500), "is_active": True})


def unseed(apps, schema_editor):
    apps.get_model("warehouse", "Unit").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0031_product_density_kg_l_alter_product_is_drop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Як пишемо в таблицях: кг, л, шт', max_length=16, unique=True, verbose_name='Скорочено')),
                ('full_name', models.CharField(blank=True, default='', help_text='Кілограм, літр — для підказки', max_length=60, verbose_name='Повна назва')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивну не видно у виборі, але старі товари з нею лишаються', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Одиниця виміру',
                'verbose_name_plural': 'Одиниці виміру',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RunPython(seed, unseed),
    ]
