# Generated by Django 5.0.14 on 2026-09-14 14:09

import apps.dealecon.models
import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '9061_lead_quality'),  # остання НАЯВНА міграція crm; дрейф crm сюди НЕ входить
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealEconomics',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dealecon_row', serialize=False, to='crm.deal')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Виручка')),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Собівартість товару')),
                ('delivery', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Доставка НП за наш рахунок')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Комісія оплати')),
                ('packaging', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Пакування (робота + матеріали)')),
                ('master_works', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Роботи майстра (+ транспорт)')),
                ('returns', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Повернення')),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Маржа')),
                ('margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Маржа, %')),
                ('sources', models.JSONField(blank=True, default=dict, help_text='По кожному компоненту: kind=fact/estimate/mixed/none + звідки взято')),
                ('flags', models.JSONField(blank=True, default=list, help_text='Що перевірити (аномалії комісії, НП без вартості…)')),
                ('is_estimate', models.BooleanField(default=False, help_text='Є хоч один ненульовий компонент-оцінка')),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveSmallIntegerField(default=1, help_text='Версія формули, якою пораховано')),
                ('locked', models.BooleanField(db_index=True, default=False, help_text='Закритий місяць: автоматичний перерахунок рядок НЕ змінює')),
            ],
            options={
                'verbose_name': 'Економіка угоди',
                'verbose_name_plural': 'Економіка угод',
            },
        ),
        migrations.CreateModel(
            name='DealEconSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_material_per_shipment', models.DecimalField(decimal_places=2, default=Decimal('22'), help_text='Коробки/стрейч/скотч: 26 221 ₴ за січень–червень ÷ 6 міс ÷ ≈200 відправлень = ≈22 ₴', max_digits=8, verbose_name='Матеріали пакування, ₴ за відправлення')),
                ('liqpay_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('1.30'), max_digits=5, verbose_name='LiqPay, %')),
                ('liqpay_rate_old_pct', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5, verbose_name='LiqPay до дати зміни, %')),
                ('liqpay_rate_change_date', models.DateField(default=datetime.date(2026, 7, 14), verbose_name='Дата зміни ставки LiqPay')),
                ('novapay_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('1.30'), max_digits=5, verbose_name='НоваПей, %')),
                ('fee_check_min_pct', models.DecimalField(decimal_places=2, default=Decimal('1.10'), max_digits=5, verbose_name='Факт комісії нижче — перевірити, %')),
                ('fee_check_max_pct', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, verbose_name='Факт комісії вище — перевірити, %')),
                ('auto_from', models.DateField(default=apps.dealecon.models.default_auto_from, help_text='Старіші угоди отримують рядок лише командою recompute_deal_economics', verbose_name='Авто-рядки для угод, створених з')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Економіка угоди: норми',
                'verbose_name_plural': 'Економіка угоди: норми',
            },
        ),
    ]
