# Generated by Django 5.0.14 on 2026-06-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0006_call_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal', models.CharField(help_text='Внутрішній номер АТС: 789/788', max_length=10, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('number', models.CharField(max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_at', models.DateTimeField(blank=True, null=True)),
                ('low_threshold', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ringingcall',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
