# Generated by Django 5.0.14 on 2026-06-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0007_phoneline_alter_callrequest_id_alter_ringingcall_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneline',
            name='busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phoneline',
            name='busy_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
