# Generated by Django 5.0.14 on 2026-07-02 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0008_phoneline_busy_phoneline_busy_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallQueueConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_shift_only', models.BooleanField(default=True, help_text='Дзвонити лише тим, хто почав робочий день')),
                ('strategy', models.CharField(default='sequential', max_length=12)),
                ('active', models.BooleanField(default=False, help_text='Чи керує черга маршрутизацією вхідних')),
            ],
        ),
        migrations.CreateModel(
            name='CallQueueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('ring_seconds', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
