# Generated by Django 5.0.14 on 2026-07-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0009_callqueueconfig_callqueuemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='callqueueconfig',
            name='ring_ext',
            field=models.CharField(blank=True, default='', help_text='Добавочний, що дзвонить ЗАРАЗ (per-turn)', max_length=16),
        ),
        migrations.AddField(
            model_name='callqueueconfig',
            name='ring_ext_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
