import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api";
type Report={total:number;contactable:number;channels:Record<string,number>;multichannel:number;marketing_consent:number;no_contact:number;no_consent:number;unsubscribed:number;invalid:number;new_today:number;new_7d:number;new_30d:number;events:Record<string,number>;anonymous_events:Record<string,number>;customers:number;orders:number;repeat_customers:number;paid_amount:string|null;attribution_note:string;manager_shares:number;manager_opened:number;contacts:{id:number;name:string;phone:string;email:string;source:string;campaign:string;consent:boolean;status:string;last_touch_at:string}[]};
export default function ContentAudience(){
 const [data,setData]=useState<Report|null>(null),[error,setError]=useState(""),[source,setSource]=useState(""),[campaign,setCampaign]=useState(""),[content,setContent]=useState(""),[query,setQuery]=useState("instruction=microcement");
 useEffect(()=>{let active=true;setError("");setData(null);api.get<Report>("/api/content-library/audience/?"+query).then(r=>{if(active)setData(r);}).catch(()=>{if(active)setError("Не вдалося отримати звіт. Перевірте доступ і спробуйте ще раз.");});return()=>{active=false;};},[query]);
 const apply=()=>setQuery(new URLSearchParams({instruction:"microcement",source,campaign,content}).toString());
 const pct=(n:number,d:number)=>d?`${(100*n/d).toFixed(1)}%`:"—";
 return <main style={{padding:24,maxWidth:1350,margin:"auto"}}><h1>База контент-лідів</h1><p>Люди, які отримали онлайн-інструкцію Wallcov. Повторні запити об’єднуються за контактом.</p>
 <form onSubmit={e=>{e.preventDefault();apply();}} style={{display:"flex",gap:12,flexWrap:"wrap",margin:"24px 0"}}>
 <label>Джерело <select value={source} onChange={e=>setSource(e.target.value)}><option value="">Усі</option>{["website","instagram","tiktok","youtube","manager","ads"].map(s=><option key={s}>{s}</option>)}</select></label>
 <label>Кампанія <input value={campaign} onChange={e=>setCampaign(e.target.value)} placeholder="utm_campaign"/></label><label>Контент <input value={content} onChange={e=>setContent(e.target.value)} placeholder="utm_content / ID"/></label><button className="btn btn-primary">Застосувати</button></form>
 {error&&<p role="alert">{error}</p>}{!data&&!error&&<p>Завантаження…</p>}
 {data&&<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:14}}>{Object.entries({"Унікальних контактів":data.total,"Із контактними даними":data.contactable,"Телефон":data.channels.phone,"Email":data.channels.email,"Кілька каналів":data.multichannel,"Згода на повідомлення":data.marketing_consent,"Нові сьогодні":data.new_today,"За 7 днів":data.new_7d,"За 30 днів":data.new_30d,"Без згоди":data.no_consent,"Відписалися":data.unsubscribed,"Некоректний контакт":data.invalid}).map(([label,n])=><section className="card" key={label} style={{padding:18}}><small>{label}</small><div style={{fontSize:32,fontWeight:700}}>{n}</div></section>)}</div>
 <p className="muted">Контактні дані вказані користувачем; доставка й належність телефону/email не підтверджені. Наявність контакту не є згодою на розсилку.</p>
 <h2>Шлях контакту після запиту інструкції</h2><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Етап</th><th>Унікальних людей</th><th>Від усіх контактів</th></tr></thead><tbody>{[["Отримали інструкцію",data.total],["Відкрили інструкцію",data.events.instruction_open||0],["Натиснули розрахунок",data.events.calculation_click||0],["Запросили розрахунок",data.events.calculation_request||0],["Покупці",data.customers]].map(([label,n])=><tr key={String(label)}><td>{label}</td><td>{n}</td><td>{pct(Number(n),data.total)}</td></tr>)}</tbody></table></div>
 <h2>Замовлення цієї аудиторії</h2><p>Замовлень: <b>{data.orders}</b> · Повторних покупців: <b>{data.repeat_customers}</b>{data.paid_amount!==null&&<> · Оплачено: <b>{Number(data.paid_amount).toLocaleString("uk-UA")} грн</b></>}</p><p className="muted">{data.attribution_note}</p>
 <h2>Робота менеджерів</h2><p>Надіслано інструкцій: {data.manager_shares} · Відкрито посилань: {data.manager_opened}. Вставлений, але не надісланий текст не рахується.</p>
 <h2>Стаття та форма</h2><p>Події від відвідувачів без прив’язаного контакту показані окремо. Перегляди соцмереж, коментарі й доставка повідомлень: немає підключеного джерела даних.</p><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Подія</th><th>Контактів</th><th>Анонімних подій</th></tr></thead><tbody>{(["article_view","article_scroll_50","article_scroll_90","lead_cta_click","lead_form_start","lead_form_submit","product_click"] as const).map(k=><tr key={k}><td>{{article_view:"Перегляд статті",article_scroll_50:"Прочитано 50%",article_scroll_90:"Прочитано 90%",lead_cta_click:"Перехід до техкарти",lead_form_start:"Початок форми",lead_form_submit:"Надіслана форма",product_click:"Перехід до товару"}[k]}</td><td>{data.events[k]||0}</td><td>{data.anonymous_events[k]||0}</td></tr>)}</tbody></table></div>
 <h2>Останні контакти</h2>{data.contacts.length===0?<p>Контактів поки немає або немає права перегляду клієнтів.</p>:<div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Клієнт</th><th>Контакт</th><th>Джерело / кампанія</th><th>Згода</th></tr></thead><tbody>{data.contacts.map(p=><tr key={p.id}><td><Link to={`/clients/${p.id}`}>{p.name}</Link></td><td>{p.phone}<br/>{p.email}</td><td>{p.source}<br/>{p.campaign}</td><td>{p.consent?"Так":"Ні"}</td></tr>)}</tbody></table></div>}</>}
 </main>;
}
