# Generated by Django 5.0.14 on 2026-09-12 17:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '9061_lead_quality'),
        ('inbox', '0022_quickreply_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_enabled', models.BooleanField(default=False, help_text='Надсилати просьби клієнтам. Вмикається лише після затвердження текстів')),
                ('texts_approved', models.BooleanField(default=False, help_text='Олег затвердив тексти просьби/нагадування')),
                ('start_date', models.DateField(blank=True, help_text='Беремо лише посилки, отримані з цієї дати', null=True)),
                ('delay_main_days', models.PositiveSmallIntegerField(default=10)),
                ('delay_test_days', models.PositiveSmallIntegerField(default=5)),
                ('remind_after_days', models.PositiveSmallIntegerField(default=5)),
                ('repeat_block_days', models.PositiveSmallIntegerField(default=60)),
                ('expire_days', models.PositiveSmallIntegerField(default=60)),
                ('window_wait_days', models.PositiveSmallIntegerField(default=21, help_text='Скільки днів чекати можливості написати')),
                ('manager_quiet_hours', models.PositiveSmallIntegerField(default=48, help_text='Тест-набір: не писати, якщо менеджер писав клієнту за стільки годин')),
                ('send_from', models.TimeField(default=datetime.time(10, 0))),
                ('send_to', models.TimeField(default=datetime.time(19, 30))),
                ('per_run_cap', models.PositiveSmallIntegerField(default=20)),
                ('test_funnel_ids', models.JSONField(blank=True, default=list, help_text='Воронки тест-наборів')),
                ('excluded_funnel_ids', models.JSONField(blank=True, default=list, help_text='Воронки, де не просимо (тести, найм, ліди)')),
                ('allowlist_contact_ids', models.JSONField(blank=True, default=list, help_text='Якщо не порожньо — надсилати лише цим контактам (тест)')),
                ('text_main', models.TextField(blank=True, default='')),
                ('text_test', models.TextField(blank=True, default='')),
                ('text_remind', models.TextField(blank=True, default='')),
                ('google_review_url', models.URLField(default='https://g.page/r/CVZX_3B9PYFbEBM/review', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налаштування відгуків',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uuid', models.UUIDField(unique=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.TextField(blank=True, default='')),
                ('text_original', models.TextField(blank=True, default='')),
                ('room', models.CharField(blank=True, default='', max_length=20)),
                ('applied_by', models.CharField(blank=True, default='unknown', max_length=10)),
                ('display_name', models.CharField(blank=True, default='', max_length=60)),
                ('anonymous', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, default='', max_length=60)),
                ('consent_site', models.BooleanField(default=False)),
                ('consent_social', models.BooleanField(default=False)),
                ('consent_version', models.CharField(blank=True, default='', max_length=40)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('products', models.JSONField(blank=True, default=list)),
                ('kind', models.CharField(default='main', max_length=12)),
                ('is_test', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'На перевірці'), ('published', 'Опубліковано'), ('hidden', 'Приховано')], db_index=True, default='pending', max_length=12)),
                ('hidden_reason', models.CharField(blank=True, default='', max_length=200)),
                ('reply_text', models.TextField(blank=True, default='')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='crm.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='crm.deal')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('keyword', 'Відповів «стоп»'), ('manual', 'Вручну'), ('form', 'Через форму')], default='manual', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_opt_out', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40, unique=True)),
                ('data', models.BinaryField()),
                ('thumb', models.BinaryField()),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reviews.review')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('main', 'Основне замовлення'), ('test', 'Тест-набір'), ('manual', 'Вручну')], default='main', max_length=12)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Заплановано'), ('waiting', 'Чекаємо'), ('would_send', 'Відправили б (відправка вимкнена)'), ('sent', 'Надіслано'), ('reminded', 'Нагадали'), ('submitted', 'Відгук отримано'), ('skipped', 'Пропущено'), ('cancelled', 'Скасовано'), ('opted_out', 'Клієнт відписався'), ('expired', 'Минув термін'), ('test', 'Тестове посилання')], db_index=True, default='scheduled', max_length=12)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('is_test', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('channel_plan', models.CharField(blank=True, default='', max_length=20)),
                ('channel_label', models.CharField(blank=True, default='', max_length=120)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('journal_at', models.DateTimeField(blank=True, help_text='Коли потрапило в журнал «відправили б»', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.channel')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_requests', to='crm.contact')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_requests', to='crm.deal')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.message')),
                ('reminder_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='review',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='reviews.reviewrequest'),
        ),
        migrations.AddConstraint(
            model_name='reviewrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('deal__isnull', False), models.Q(('kind', 'manual'), _negated=True)), fields=('deal',), name='reviews_one_auto_request_per_deal'),
        ),
    ]
