"""Технічні завдання для ШІ-художника: як виглядає кожне декоративне покриття Wallcov (25.09.2026).

Склали три агенти (художник матеріалів, 3D-спеціаліст з текстур, дизайнер інтерʼєрів) за регламентом
Projects/Wallcov-CRM/Правила-генерации-контента.md, базою знань CRM і реальними фото бібліотеки.
Використовується в aiimage для блогів з label_ai (Wallcov): опис фактури + реальне фото-зразок як референс.
"""
SPECS = {
 "мокрий шовк": {
  "surface": "Wall finished in wet-silk decorative paint: an almost flat, continuous satin-pearlescent surface. Soft irregular overlapping brush/plastic-trowel strokes roughly 10–30 cm, multidirectional with torn, feathered edges, visible mainly where light hits at a grazing angle. Low contrast: tone shifts come from light playing inside the thin layer, not from different colours. Up close a very fine suede-like pearly micro-sheen, no grains or glitter. The highlight is a broad soft sheen band following the light source direction; the wall away from it is calm and even. Hand-applied, non-repeating.",
  "light": "Wet-silk decorative plaster wall: smooth satin surface with soft pearlescent sheen, overlapping hand-trowelled strokes 10–35 cm long, subtle tone shifts of the same pigment, directional anisotropic shimmer following the trowel strokes. Sheen appears only where the window light hits at a grazing 25° angle and fades to calm satin elsewhere. No particles, no veins. Photographed on a full-frame camera, 35mm lens, f/5.6, ISO 400, natural side window light, slight sensor grain, true scale next to a wall outlet and bed headboard.",
  "negative": "no sand, no quartz grain, no glitter, no sparkles, no marble veins, no concrete, no microcement, no relief, no cracks, no metallic foil, no mirror gloss, no repeated stamp pattern, no hard outlines between strokes, no two-tone split; marble veins, mirror gloss, chrome, metallic foil, glitter, sparkles, repeating clouds, tiled pattern, plastic CG sheen, HDR halos, over-sharpened, flat matte paint, painted white highlights, oversized strokes",
  "room": "Photorealistic interior of a real city apartment bedroom, the decorative wall behind a low upholstered headboard in warm grey velvet, seen at a 30-degree angle from the doorway at eye level. Soft side daylight from a window with sheer curtains just out of frame on the left, two small bedside lamps glowing warm. Light oak floor, cream bedding, a folded linen throw, a book on the nightstand. Panel radiator under the side window, sockets beside the bed, plain white ceiling. Calm, lived-in, 28mm lens, vertical lines straight.",
  "summary_uk": "Гладкий сатиново-перламутровий шар з м'якими рваними мазками 10–30 см, перелив лише у світлі, без зерна й рельєфу."
 },
 "мермі шовк": {
  "surface": "Wall in Mermi silk decorative paint, light colour: a smooth, flawless, almost uniform satin surface with very subtle pearly cloud-like tonal drifts 15–40 cm across and no visible edges. From a distance it reads as an elegant calm wall; near windows and grazing light a delicate silky shimmer appears and drifts across the plane. No texture, grains or relief; soft, broad highlight following the light direction, everything else quiet. Subtle, hand-applied, non-repeating.",
  "light": "Mermi silk decorative finish on a white wall with classic panel mouldings: very low-contrast white-on-ivory soft clouds 20–60 cm across, velvety satin sheen, no particles, almost flat surface. The pattern is revealed only by grazing daylight from a window at the end of the corridor, visible along the wall in perspective. Wall outlets and switches show true scale. Real apartment photo, 24mm lens, f/8, ISO 200, exposure slightly reduced to keep highlight detail, fine natural grain.",
  "negative": "no strong contrast, no marble veins, no concrete clouds, no glitter, no sand, no relief, no high-gloss mirror reflections, no plastic uniform paint, no repeated pattern; high contrast grey patches, marble, glitter, metallic, sand texture, flat CG white fill, clipped wall, blown highlights, tiled clouds, dirty stains, HDR",
  "room": "Photorealistic neoclassical corridor in a real Ukrainian city apartment, the decorative wall with thin painted moulding frames running along the corridor, white interior doors with casings and brass handles, light grey oak laminate, white skirting and a modest ceiling cornice. Daylight spilling from an open bedroom door, a slim bench with a knitted cushion, a round mirror on the opposite side. Camera from the entrance at 1.4 m, one-point perspective looking down the corridor, 26mm lens, calm airy mood, no clutter.",
  "summary_uk": "Дуже делікатний шовковий перелив у м'яких хмарах 15–40 см, у світлих тонах майже непомітний, без зерна."
 },
 "галатея": {
  "surface": "Wall in Galateya pearlescent sand decorative coating: a thin mineral layer with dense fine sand-like grain over the whole surface, arranged into irregular torn cloud-islands 3–15 cm with feathered, crumbling edges, lighter metallic-pearl islands over a slightly darker base. Brushed in short chaotic strokes. In the direction of the light source the grains flash with fine, numerous silvery sparkles in a soft-edged zone; outside it the wall looks like calm satin sand. Micro-relief barely perceptible, no coarse texture.",
  "light": "Galatea decorative pearl plaster: suede-like fine micro-grain surface with irregular frosty-edged clouds 8–30 cm, darker satin ground and lighter pearlescent patches of the same pigment. A soft luminous sheen blooms only where side light reaches the mirror angle, the rest stays deep velvety matte-satin. Micro-grain reads as suede, not glitter. Real interior photo, 35mm lens, f/5.6, ISO 400, single side lamp, natural falloff, faint sensor noise.",
  "negative": "no uniform glitter, no large sequins, no snow, no star sparkles, no coarse builder sand, no stucco relief, no marble veins, no smooth silk without grain, no repeating stamp; glitter, star sparkles, snow flakes, coarse sand, chrome, metallic foil, marble veins, uniform sheen, plastic CG, HDR halos, tiled pattern, watermark, logo",
  "room": "Photorealistic evening living room in a modern city apartment, the decorative wall behind a cream three-seat sofa, grazed from above by two adjustable track spotlights so light falls along the surface. A window with linen curtains on the adjacent left wall, radiator beneath the sill. Walnut coffee table, grey velvet armchair, pale wool rug, a single brass floor lamp. Camera from the room corner at 1.3 m, 30-degree angle to the wall, 28mm lens, deep calm shadows, no artwork on the wall.",
  "summary_uk": "Дрібний перламутровий пісок у рваних острівцях 3–15 см, найактивніше іскріння серед пісків, тільки в зоні світла."
 },
 "вельвет люкс": {
  "surface": "Wall in Velvet Lux pearlescent marmorino: a thin mineral plaster with irregular torn low islands, 2–15 cm, raised only fractions of a millimetre, with jagged crumbly edges, scattered chaotically and sometimes merging. The island tops are finely granular and slightly rough with rare tiny pearl glints; the troweled areas between them are smooth, low and satin. Near-matte velvety pearlescent sheen; grazing light reveals the fine edges with thin soft shadows, frontal light keeps it quiet. Hand-troweled, non-repeating.",
  "light": "Velvet Lux decorative plaster in deep chocolate brown: velvety pearlescent satin with low hand-trowelled relief, smooth raised plateaus and slightly rough recessed zones with torn irregular edges (under 1 mm deep). Rare tiny iridescent glints flash only where the grazing light hits the mirror angle. From a distance it reads as soft velvet. Evening interior photo, 35mm, f/4, ISO 800, warm wall grazers and ceiling spots, preserved shadow detail, natural sensor grain.",
  "negative": "no thick bark-like relief, no deep shadows, no cracks, no glitter coating, no literal continent map, no stamped repeating spots, no mesh/lace pattern, no glossy plastic; uniform glitter, starry sky, heavy stone relief, bark, crocodile skin, deep shadows, regular grid, foil, plastic shine, tiled texture, crushed blacks, flat dark paint, HDR",
  "room": "Photorealistic open-plan living room with a small dining zone in a real city apartment, the decorative wall behind a beige corner sofa, viewed from the dining table at a 35-degree angle. Long chocolate-brown curtains on a window along the adjacent wall, radiator under the sill, soft side daylight sliding along the wall. Walnut dining table, taupe cushions, a caramel wool throw, a modern pendant with glass globes. Light oak floor, sockets near the sofa, 28mm lens, warm family atmosphere.",
  "summary_uk": "Перламутровий мармарин: низькі рвані острівці 2–15 см із зернистим верхом на гладкій сатиновій основі, майже матовий."
 },
 "вельвет луна": {
  "surface": "Wall in Velvet Luna decorative paint, classic trowel-stroke technique: a nearly flat continuous velvety-satin surface covered with large soft overlapping trowel strokes about 15–40 cm, elongated leaf- or feather-like, multidirectional, with gentle occasionally torn stroke ends. Adjacent strokes catch light differently, producing a calm pearlescent shimmer that shifts with viewing angle. Up close a fine suede-like micro-texture, no grains, no sparkle, practically no relief. Low contrast, hand-applied, evenly distributed, non-repeating.",
  "light": "Velvet Luna decorative finish, trowel-stroke technique: almost smooth continuous silky-satin surface with large soft overlapping hand-trowel strokes 15–40 cm long, gentle same-pigment tone shifts, calm pearlescent sheen that changes with stroke direction. No quartz, no glass, no glitter, no relief islands. Grazing daylight from a side window at about 25° reveals the strokes; true scale next to wall outlets and a ceiling cornice. Real apartment photo, 35mm, f/8, ISO 200, natural grain.",
  "negative": "no crocodile skin, no small closed cells, no scales, no craquelure, no mesh or lace lines, no quartz grain, no glitter, no relief islands, no flat uniform paint, no giant slabs, no marble veins; web network, lace, cell pattern, crocodile skin, bark, bumpy texture, quartz, glass sparkles, glitter, glowing outlines, flat paint, huge plates, continent map, marble veins, CG render, tiling",
  "room": "Photorealistic bright bedroom in an ordinary city apartment, the decorative wall behind a grey-beige quilted headboard, seen from near the window at a 30-degree angle. A white interior door with casing on the adjacent wall, two chrome globe pendants hanging over small nightstands, light oak floor, white and pale grey bedding, a knitted throw. Soft morning daylight grazing along the wall from the left, plain white ceiling with a modest cornice. 28mm lens, eye level, calm and airy, nothing hung on the wall.",
  "summary_uk": "Великі м'які перекриття кельми 15–40 см на оксамитово-сатиновій майже плоскій поверхні, без луски й зерна."
 },
 "патера": {
  "surface": "Wall in Pattera mineral textured plaster, 'world map' technique: about 75% of the wall is a well-troweled, almost smooth matte-satin mineral plane; the rest consists of small irregular recessed eroded islands 1–8 cm with jagged, finely serrated edges. Inside the islands a fine-grained mineral roughness, shallow pits and tiny pores; they sit slightly below the smooth plane, never raised crusts. Islands vary in shape, density and spacing, scattered naturally. Grazing light casts only hairline shadows at the edges. Matte natural stone character, hand-troweled, non-repeating.",
  "light": "Pattera textured decorative plaster: smooth satin base with low hand-applied mineral relief islands 1–6 cm with torn irregular edges, 0.5–1.5 mm high, grouped in random clusters; pearlescent sheen catches only on the relief crests, casting tiny shadows under strong grazing side light at 20°. Clearly tactile, not silk. Same pigment for base and relief. Real photo, 35mm, f/8, ISO 200, window light raking along the wall, true scale next to a door frame and outlet.",
  "negative": "no pearlescent silk look, no literal continents, no big crusts, no deep shadows, no cracks, no stone fractures, no uniform wrinkled stucco all over, no tiles, no repeating stamp, no glitter; smooth silk, pearlescent flat wall, stone bark, deep crevices, lava foam, stamped identical islands, tiling, metallic foil, glitter, marble veins, blown highlights, CG render",
  "room": "Photorealistic warm living room in a real city apartment with Mediterranean-modern furnishing, the decorative wall behind a low oat-linen sofa, low-angle afternoon daylight entering from a window on the right and grazing across the wall. Travertine side table, oak coffee table, terracotta ceramics, a jute rug, an olive tree in a clay pot. Radiator under the window sill, sockets near the floor, plain ceiling. Camera from the opposite corner at 1.3 m, 40-degree view of the wall, 28mm lens, relaxed lived-in mood.",
  "summary_uk": "Гладка мінеральна площина (~75%) з дрібними заглибленими рваними острівцями 1–8 см, матова, без перламутру й тріщин."
 },
 "піски": {
  "surface": "Wall in pearlescent 'sand effect' decorative coating: a thin layer with dense fine uniform grain across the whole surface, gathered into soft irregular cloud clusters 5–25 cm with feathery edges that break up into individual grains, over a slightly darker satin base. Short multidirectional brush marks visible within the clusters. In the reflection zone of the light the grains glow with a fine metallic-pearl shimmer and a few tiny brighter glints; elsewhere the surface is calm and velvety. Micro-relief extremely low, no coarse sand.",
  "light": "Sands decorative plaster in deep navy: darker satin base with fine pearlescent silver sand grains 0.1–0.4 mm gathered in irregular fan-shaped trowel strokes and clouds 10–30 cm, with calm darker gaps between them. Grains glint as tiny points only under grazing side light, denser in the light clouds and sparse in the gaps. Real interior photo, 35mm, f/5.6, ISO 400, single warm wall sconce raking at 20°, natural grain.",
  "negative": "no coarse sand, no stucco relief, no uniform glitter, no large flakes, no concrete, no smooth silk, no marble veins, no repeated blotches; uniform glitter, starry night, confetti, big sequins, star-filter flares, foil, chrome, marble veins, CG noise, tiled texture, over-sharpened grain, flat matte paint",
  "room": "Photorealistic evening bedroom in a modern city apartment, the decorative wall behind a bed with crisp white and silver-grey bedding, two wall sconces directing warm light downward along the wall surface. A window with dusk-blue light on the adjacent wall, radiator under the sill, light oak floor, nickel details, a dusty-blue velvet bench at the foot of the bed. Camera from the room corner at 1.3 m, 35-degree angle to the wall, 28mm lens, calm shadows between the lit zones.",
  "summary_uk": "Дрібне металізоване зерно в розсипчастих хмарах 5–25 см на сатиновій основі, мерехтіння тільки у світлі."
 },
 "мікроцемент": {
  "surface": "Wall finished in microcement: a seamless, continuous mineral surface with a soft concrete character. Gentle cloudy variations of light and mid grey 30–100 cm, with faint arc- and fan-shaped trowel marks 10–40 cm and occasional fine hairline tool scratches. Up close a very fine sandy-cement micro-texture with tiny dark pinholes, slightly rough, under a satin protective varnish. Matte-to-satin broad soft sheen, no mirror reflections, no sparkle. Corners and niches wrapped in the same material without joints.",
  "light": "Microcement wall finish: seamless monolithic matte cement surface with soft cloudy tone variations of one grey pigment, faint arc-shaped trowel marks and tiny pinholes, protected by a satin sealer that brightens only slightly near the light source. Crisp niche edges with 1–2 mm rounded corners. No pearl, no sparkle. Real bathroom photo, 28mm, f/8, ISO 200, soft window light from the side at 30°, natural grain, true scale next to faucet and niche.",
  "negative": "no formwork joints, no tie holes, no large air pores, no marble veins, no mirror gloss, no pearlescent shimmer, no glitter, no tiles, no seams, no plastic uniform paint, no cracks; concrete formwork panels, tie holes, joints, pearl, glitter, marble veins, mirror gloss, grunge dirt, cracks, tiled pattern, plastic CG, flat paint",
  "room": "Photorealistic warm urban living room in a real city apartment, the decorative wall behind a sand-coloured bouclé sofa, viewed from the dining area at a 35-degree angle. Side daylight from a window on the left with radiator below, black track lights on the plain ceiling, light oak floor, a black metal floor lamp, a large fiddle-leaf fig, linen cushions in oat and rust. Sockets at skirting level, an interior door with casing at the frame edge. 28mm lens, eye level, calm and modern, no artwork on the wall.",
  "summary_uk": "Безшовний мінеральний сірий шар з м'якими дуговими слідами кельми, дрібні пори, сатиновий лак, без блиску й швів."
 },
 "міо глос": {
  "surface": "Wall in Mio Gloss decorative coating: an almost smooth, finished satin-pearlescent metallic base that subtly changes brightness with viewing angle. Very fine sub-millimetre quartz grain is scattered unevenly, gathering into irregular ragged cloud clusters 5–25 cm whose edges dissolve into individual grains; calm base areas between them. Under directional or grazing light the clusters glow softly a little lighter than the base; in shade the pattern becomes quiet. Medium reflectance, no individual sparkles, no relief, non-repeating hand application.",
  "light": "Mio Gloss decorative plaster, chaotic technique: nearly smooth fine-textured satin-pearlescent base with angle-dependent sheen, very fine quartz grain scattered unevenly into cloud-like clusters 5–25 cm whose edges thin out and dissolve, calm base between clusters. Quartz is quieter than the pearl base and reveals structure only locally where light grazes. Warm bedroom photo, 35mm, f/5.6, ISO 400, bedside lamp raking at 20°, subtle grain.",
  "negative": "no cloudy concrete, no flakes, no peeling paint, no raised relief, no glitter, no snow, no star sparkles, no diagonal streaks in chaotic technique, no veins, no outlines, no bald empty patches, no tiles, no marble, no cracks, no sponge pattern; coarse sand, flakes, bumpy stucco, painted white clouds, blurred concrete, outlined clusters, diagonal veins, uniform glitter, diamonds, snow, stars, foil, mirror lacquer, tiling, CG render",
  "room": "Photorealistic bedroom in a real city apartment with soft modern-classic styling, the decorative wall behind a beige velvet headboard, two glass table lamps on oak nightstands casting warm light along the wall. Cream curtains on a window to the left, radiator under the sill, light oak floor, cream and sand bedding, a small upholstered bench. Plain ceiling with a restrained cornice and a modest chandelier. Camera from the corner at 1.3 m, 35-degree angle to the wall, 28mm lens, cosy evening mood.",
  "summary_uk": "Гладка металізовано-перламутрова основа з дрібним кварцом у рваних хмарах 5–25 см, світиться лише в напрямленому світлі, без іскор."
 },
 "елеганті": {
  "surface": "Wall in Eleganti pearlescent sand coating: a thin semi-matte layer with fine, uniform sand-like grain across the whole surface. Soft, low-contrast cloud clusters 10–40 cm built from short criss-cross brush strokes 3–10 cm long. Restrained, gentle pearly sheen: in the reflection zone a broad soft glow with delicate fine shimmer, elsewhere a calm velvety sand surface. Almost no relief, no coarse particles, subtle and elegant, hand-applied, non-repeating.",
  "light": "Eleganti decorative finish: restrained fine-grain velvety-sand surface, even micro-texture 0.1–0.3 mm, subtle same-pigment tone shifts and soft cross-hatched trowel strokes 5–25 cm where a faint silvery pearl micro-shimmer appears only near the light source. Calm, modest, understated. Real Scandinavian-style room photo, 35mm, f/8, ISO 200, soft daylight from a side window at 30°, natural grain, true scale next to a skirting board and outlet.",
  "negative": "no strong glitter, no bright sparkles, no coarse sand, no stucco, no concrete, no marble veins, no high contrast blotches, no mirror gloss, no plain flat paint; bright pearl silk, big clouds, glitter, coarse sand, marble, repeating parallel stripes, tiled strokes, plastic CG, blown highlights, HDR",
  "room": "Photorealistic bright Scandinavian-style corridor in a real city apartment, the decorative wall running along one side, viewed from the entrance at a sharp angle so daylight from an open room door slides along it. White interior doors with casings, a white handleless wardrobe opposite, light oak floor, white skirting, a small grey wool runner, a slim oak bench. Plain ceiling with recessed spots. Camera at 1.4 m, 26mm lens, quiet, clean and lived-in, with shoes and a tote bag near the bench.",
  "summary_uk": "Стриманий напівматовий дрібний пісок з перехресними мазками пензля, делікатне мерехтіння, слабше за Галатею."
 },
 "слейт / арт-бетон": {
  "surface": "Wall in decorative art-concrete / slate plaster. Art-concrete version: large formwork-like panels with slightly raised, ragged joint lines, matte cement skin with scattered clusters of small air cavities 3–20 mm with sharp edges and inner shadow, darker tonal smudges near the joints. Slate version: uniform fine-grained sandy stone surface with sparse 1–5 mm mineral inclusions — tiny translucent mica flakes that flash only at certain angles and dark stone crumbs. Matte natural look, hand-troweled, irregular, non-repeating.",
  "light": "Art-concrete decorative plaster wall: cast-in-place concrete look with large panels divided by slightly raised rough formwork joints, matte mineral grey surface with darker drips near joints and random clusters of small air-pocket cavities 2–15 mm, each with its own shadow under grazing light. No pearl, no sheen. Loft interior photo, 28mm, f/8, ISO 200, window light raking along the wall at 20°, natural grain, true scale next to an outlet and door.",
  "negative": "no brick pattern, no uniform tile grid, no glitter, no sequins, no deep craters, no dirt stains, no structural cracks, no repeating pore stamp, no glossy polish, no pearlescent silk; regular grid of holes, identical repeating panels, CG clean concrete, pearl, glitter, marble veins, deep cracks, grunge dirt, star sparkles, microcement smoothness, plastic",
  "room": "Photorealistic living loft in an ordinary city apartment, the decorative wall behind a cognac leather sofa, seen from the room corner at a 35-degree angle so the pattern recedes in perspective. A window with radiator on the right wall, side daylight grazing the wall, black steel floor lamp, oak coffee table, sand linen cushions, a tall olive tree. Light oak floor, interior door with casing at the frame edge, sockets near the skirting. 28mm lens, eye level, understated industrial mood, no artwork on the wall.",
  "summary_uk": "Арт-бетон — плити з рваними швами й раковинами; Slate — дрібнозерниста кам'яна площина з поодинокими лусками слюди, матово."
 },
 "венеціанка": {
  "surface": "Wall in polished Venetian lime plaster: multiple thin translucent layers burnished to a smooth, glassy semi-gloss finish with visible depth. Soft cloudy tonal transitions and angular overlapping trowel marks 5–25 cm, with occasional short fine darker hairline veins. Up close a mirror-smooth film with faint tool scratches and tiny pores beneath. Window and lamp reflections appear as soft-edged bright patches that move with the viewpoint; away from them the surface shows rich layered depth. Hand-burnished, irregular, non-repeating.",
  "light": "Venetian polished lime plaster: multi-layered same-pigment tones with depth, overlapping trowel planes 5–30 cm with crisp thin edges, burnished wax topcoat giving a true mirror-like reflection of the window that slightly wobbles over layer boundaries. Fine dark trowel-edge lines, not marble veins. Real bathroom photo, 28mm, f/8, ISO 200, daylight from a side window, reflection visible on the wall, natural grain.",
  "negative": "no ceramic tile marble, no printed marble veins, no plastic gloss without depth, no flat matte paint, no glitter, no sand grain, no repeating pattern, no overexposed white glare; fake marble veins, regular veining, plastic lacquer, car paint, chrome, uniform gloss without reflections, painted white highlight blobs, tiled pattern, HDR halos, matte finish",
  "room": "Photorealistic contemporary-classic living room in a real city apartment, the decorative wall behind a slim walnut console and a cream bouclé sofa, viewed from the room corner at a 40-degree angle so the tall window on the adjacent wall reflects softly in its surface. Radiator under the sill, brass table lamp, marble side table, deep green velvet armchair, pale wool rug, light oak parquet. Plain ceiling with a restrained cornice. 28mm lens, eye level, elegant yet lived-in, no artwork on the wall.",
  "summary_uk": "Полірована багатошарова вапняна поверхня з глибиною, кутастими слідами кельми й тонкими прожилками, чіткі м'які відблиски."
 },
 "антикатура": {
  "surface": "Wall in Anticatura lime plaster with natural travertine character: a matte mineral limestone surface with long horizontal drag bands 10–40 cm, soft wavy tonal stripes and irregular groups of open pores and small elongated cavities 2–15 mm with ragged edges. Fine-grained chalky roughness, occasional ochre and brown mineral specks and a few translucent marble crumbs. No seams, no tiles. Grazing light reveals pores and horizontal drag lines; frontal light keeps it calm. Hand-troweled, irregular, non-repeating.",
  "light": "Anticatura aged-stone lime plaster: matte mineral limestone surface in warm off-white, uneven tactile relief up to 1.5 mm with small irregular pits and cavities, sparse ochre specks and rare translucent golden mica flakes 1–4 mm that flash only at the exact mirror angle. Horizontal travertine-like streaks in some areas. Real Mediterranean interior photo, 35mm, f/8, ISO 200, low raking daylight at 20°, natural grain, true scale next to a door frame.",
  "negative": "no tile joints, no grid, no deep craters, no rock fractures, no pearlescent shimmer, no glitter, no sponge stamp, no repeating pores, no plastic gloss, no printed stone photo; uniform glitter, starry sparkles, identical pits, tiled texture, CG stone, grunge dirt, deep cracks, plastic shine, marble veins, concrete joints, HDR",
  "room": "Photorealistic wabi-sabi living room in a real city apartment, the decorative wall behind a low oat-linen sofa, late-afternoon sun entering low through a window on the right and grazing across the wall. Olive-wood stool, terracotta vase with dried branches, jute rug, a travertine coffee table, a rattan armchair. Radiator under the window sill, light oak floor, simple plain ceiling. Camera from the opposite corner at 1.2 m, 40-degree view of the wall, 28mm lens, slow, warm and lived-in mood.",
  "summary_uk": "Матовий вапняний «травертин»: горизонтальні протяжки, групи пор 2–15 мм, вохристі вкраплення, без швів і блиску."
 }
}
GENERAL = "Real photograph, not a render: shot on a full-frame or high-end phone camera with natural lens imperfections, subtle sensor grain, one motivated main light source, highlights only where light physically falls, true-to-scale texture relative to sockets (8 cm), doors and skirting, verticals corrected. Avoid: CGI render, 3D render look, video game texture, tiled/repeating pattern, seamless texture tiling, visible texture seams, moire, over-sharpened, HDR halos, clarity overdone, oversaturated, plastic sheen, glossy car paint, chrome, liquid metal, metallic foil, uniform glitter, sparkles everywhere, star filter, bokeh sparkles, fake marble veins, painted-on highlights, white blobs, glowing outlines, lace/web network, crocodile skin, bark, stucco popcorn, split-screen, sharp color boundary, distorted perspective, warped outlets, impossible doorways, text artifacts, watermark, logo"


def _norm(name):
    return (name or "").lower().replace("’", "'").replace("ʼ", "'").strip()


ALIASES = {"мокрий шовк": ["шовк", "silk", "sirena"], "мермі шовк": ["мермі", "mermi"], "галатея": ["galatea", "galathea"],
           "вельвет люкс": ["velvet lux", "люкс"], "вельвет луна": ["luna", "луна"], "патера": ["pattera", "patera"],
           "піски": ["піщинк", "пісок", "sand"], "мікроцемент": ["microcement", "мікробетон", "topciment"],
           "міо глос": ["mio", "міо"], "елеганті": ["eleganti", "елеган"], "слейт / арт-бетон": ["слейт", "арт-бетон", "артбетон", "slate"],
           "венеціанка": ["венеціан", "venetian"], "антикатура": ["anticatura", "антикат"]}


def find_material(text):
    t = _norm(text)
    for mat, al in ALIASES.items():
        if mat in t or any(a in t for a in al):
            return mat
    return ""


def spec_for(material):
    """Фрагмент промпту: фактура + світло + заборони для матеріалу (порожньо, якщо ТЗ ще немає)."""
    s = SPECS.get(_norm(material)) or {}
    parts = [GENERAL, s.get("surface", ""), s.get("light", ""), ("Avoid: " + s["negative"]) if s.get("negative") else ""]
    return " ".join(p for p in parts if p).strip()
