# Generated by Django 5.0.14 on 2026-06-25 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_department_permissions_and_more'),
        ('crm', '9003_deal_stage_changed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='actions',
            field=models.JSONField(blank=True, default=list, help_text='Дії при потраплянні на стадію'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='delay_hours',
            field=models.IntegerField(default=0, help_text='Затримка дії, годин (дожим)'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='description',
            field=models.TextField(blank=True, help_text='Опис правила людською мовою (для навчання)'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='entry_conditions',
            field=models.JSONField(blank=True, default=list, help_text='Умови входу на стадію'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='note_to_staff',
            field=models.TextField(blank=True, help_text='Підказка співробітнику'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='actor',
            field=models.CharField(blank=True, default='', help_text='Хто дію зробив (менеджер / AI-агент / Система)', max_length=80),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger',
            field=models.CharField(choices=[('manager_reply', 'Менеджер/AI відповів'), ('client_reply', 'Клієнт відповів'), ('ready_buy', 'Готовність купити'), ('payment', 'Оплата отримана'), ('time_in_stage', 'Простій на стадії (дожим)'), ('field_changed', 'Змінилось поле'), ('item_added', 'Додано товар')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='social_link',
            field=models.CharField(blank=True, default='', help_text='Посилання на акаунт клієнта в месенджері (IG/TG/FB)', max_length=300),
        ),
        migrations.AlterField(
            model_name='deal',
            name='card_fields',
            field=models.JSONField(blank=True, default=list, help_text='Кастомні поля картки [{label, value}]'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='qualification',
            field=models.JSONField(blank=True, default=dict, help_text='Анкета виявлення потреби (переноситься з ліда)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='source',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('viber', 'Viber'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('call', 'Звонок'), ('google_business', 'Google Бизнес'), ('other', 'Другое'), ('site', 'Сайт wallcovdec'), ('wholesale', 'Опт / дилери'), ('designers', 'Дизайнери / прораби'), ('tiktok', 'TikTok')], default='other', max_length=24),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage_changed_at',
            field=models.DateTimeField(blank=True, help_text='Коли востаннє змінилась стадія (для днів на стадії)', null=True),
        ),
        migrations.AlterField(
            model_name='dealitem',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Знижка на позицію, %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('viber', 'Viber'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('call', 'Звонок'), ('google_business', 'Google Бизнес'), ('other', 'Другое'), ('site', 'Сайт wallcovdec'), ('wholesale', 'Опт / дилери'), ('designers', 'Дизайнери / прораби'), ('tiktok', 'TikTok')], default='other', max_length=24),
        ),
        migrations.AlterField(
            model_name='stage',
            name='auto_only',
            field=models.BooleanField(default=False, help_text='Статус ставиться ТІЛЬКИ автоматизацією — ручне переміщення заборонено'),
        ),
        migrations.CreateModel(
            name='GlobalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('products', 'Товари'), ('sales', 'Продажі / воронки'), ('automation', 'Автоматизації'), ('payments', 'Платежі'), ('novaposhta', 'Нова Пошта'), ('checkbox', 'Чеки (Checkbox)'), ('warehouse', 'Склад'), ('followup', 'Дожими'), ('general', 'Загальні')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, help_text='Markdown, редагується менеджером')),
                ('priority', models.IntegerField(default=100)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_rules', to='crm.funnel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['block', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('warehouse', 'Склад'), ('tinting', 'Тонування'), ('manager', 'Менеджер'), ('followup', 'Дожим'), ('other', 'Інше')], default='other', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Запропоновано'), ('open', 'Відкрита'), ('in_progress', 'В роботі'), ('done', 'Виконана'), ('canceled', 'Скасована')], db_index=True, default='open', max_length=14)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_agent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.deal')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounts.department')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead')),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
