# Generated by Django 5.0.14 on 2026-06-25 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9004_automationrule_actions_automationrule_delay_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('autonomous', models.BooleanField(default=True, help_text='True=агент сам виконує дії; False=пропонує')),
                ('auto_on_reply', models.BooleanField(default=True, help_text='Запускати агента на кожну відповідь клієнта')),
                ('model', models.CharField(default='claude-sonnet-4-6', max_length=40)),
                ('system_extra', models.TextField(blank=True, help_text='Додаткова інструкція агенту')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='lead', max_length=10)),
                ('trigger', models.CharField(default='manual', max_length=20)),
                ('model', models.CharField(blank=True, max_length=40)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('tasks_created', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='crm.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='crm.lead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
