# Generated by Django 5.0.14 on 2026-06-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9006_paylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='checkbox_receipt_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='deal',
            name='checkbox_relation_id',
            field=models.CharField(blank=True, default='', help_text='pre_payment_relation_id для звʼязку аванс→фінал', max_length=64),
        ),
        migrations.AddField(
            model_name='deal',
            name='checkbox_url',
            field=models.TextField(blank=True, default='', help_text='Фіскальна ссылка на чек'),
        ),
    ]
