# Generated by Django 5.0.14 on 2026-06-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9007_deal_checkbox_receipt_id_deal_checkbox_relation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkbox_receipt_id',
            field=models.CharField(blank=True, default='', help_text='ID чека Checkbox для цього платежу', max_length=64),
        ),
    ]
