# Generated by Django 5.0.14 on 2026-06-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9009_alter_payment_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_seen',
            field=models.BooleanField(default=True, help_text='Бейдж непереглянуто: False=клієнт написав і не відповіли, True=відповіли'),
        ),
    ]
