# Generated by Django 5.0.14 on 2026-06-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9011_dialoganalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='np_data',
            field=models.JSONField(blank=True, default=dict, help_text='Повна форма Доставка НП'),
        ),
        migrations.AddField(
            model_name='deal',
            name='np_delivery_date',
            field=models.DateField(blank=True, help_text='Бажана дата доставки', null=True),
        ),
    ]
