# Generated by Django 5.0.14 on 2026-06-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9012_deal_np_data_deal_np_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, default='', help_text='По батькові', max_length=120),
        ),
        migrations.AddField(
            model_name='contact',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Нік / імʼя з месенджера (оригінал)', max_length=150),
        ),
    ]
