# Generated by Django 5.0.14 on 2026-06-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9013_contact_middle_name_contact_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='ref_photos',
            field=models.JSONField(blank=True, default=list, help_text='Скріни/фото від клієнта (data-URL) — показуються складу'),
        ),
    ]
