# Generated by Django 5.0.14 on 2026-06-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9014_deal_ref_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='analyst_model',
            field=models.CharField(default='claude-sonnet-4-6', max_length=40),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='cache_enabled',
            field=models.BooleanField(default=True, help_text='Prompt caching — економія на повторному контексті'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='priority_enabled',
            field=models.BooleanField(default=True, help_text='ИИ-РОП авто-приоритет чатов (крон 5хв)'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='priority_model',
            field=models.CharField(default='claude-haiku-4-5', max_length=40),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='suggest_model',
            field=models.CharField(default='claude-sonnet-4-6', max_length=40),
        ),
    ]
