# Generated by Django 5.0.14 on 2026-06-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9015_agentconfig_analyst_model_agentconfig_cache_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='analyst_auto',
            field=models.BooleanField(default=False, help_text='Коуч-аналіз САМ при відкритті картки (Opus). False = тільки по кнопці'),
        ),
    ]
