# Generated by Django 5.0.14 on 2026-06-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9016_agentconfig_analyst_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(db_index=True, max_length=60)),
                ('model', models.CharField(max_length=40)),
                ('in_tok', models.IntegerField(default=0)),
                ('out_tok', models.IntegerField(default=0)),
                ('cache_read', models.IntegerField(default=0)),
                ('cache_write', models.IntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0)),
            ],
        ),
    ]
