# Generated by Django 5.0.14 on 2026-06-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9017_aiusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusage',
            name='est',
            field=models.BooleanField(default=False, help_text='True=оцінка (історія до логування), False=точно'),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
