# Generated by Django 5.0.14 on 2026-07-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9018_aiusage_est_aiusage_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='kp_history',
            field=models.JSONField(blank=True, default=list, help_text='Історія КП/накладних: [{ts,total,subtotal,discount,note,by,items:[{name,qty,price,discount_pct,total}]}]'),
        ),
    ]
