# Generated by Django 5.0.14 on 2026-07-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9019_deal_kp_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Знімок собівартості на момент продажу (для чесної маржі в історії)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('liqpay', 'LiqPay'), ('checkbox', 'Checkbox'), ('cash', 'Наличные'), ('bank', 'Банк'), ('np_cod', 'Накладений платіж НП'), ('reqs', 'Реквізити')], max_length=16),
        ),
    ]
