# Generated by Django 5.0.14 on 2026-07-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9021_contact_shared_with'),
        ('warehouse', '0010_product_track_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealitem',
            name='custom_name',
            field=models.CharField(blank=True, default='', help_text='Своя позиція НЕ з номенклатури: без складського обліку і списання', max_length=200),
        ),
        migrations.AlterField(
            model_name='dealitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_items', to='warehouse.product'),
        ),
    ]
