# Generated by Django 5.2 for Wallcov CRM — 2026-07-26
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import apps.crm.models


def link_existing_projects(apps, schema_editor):
    ZamerProject = apps.get_model("crm", "ZamerProject")
    Contact = apps.get_model("crm", "Contact")
    Deal = apps.get_model("crm", "Deal")
    for project in ZamerProject.objects.all().iterator():
        payload = project.payload if isinstance(project.payload, dict) else {}
        contact_id = payload.get("clientId") or payload.get("client_id")
        deal_id = payload.get("dealId") or payload.get("deal_id")
        updates = []
        contact = None
        deal = None
        try:
            if contact_id:
                contact = Contact.objects.filter(pk=int(contact_id)).first()
        except (TypeError, ValueError):
            pass
        try:
            if deal_id:
                deal = Deal.objects.filter(pk=int(deal_id)).first()
        except (TypeError, ValueError):
            pass

        # Не закрепляем исторически смешанные client/deal пары. Если payload
        # знает только сделку, безопасно берём клиента из самой сделки.
        if deal and deal.contact_id:
            if contact is None:
                contact = deal.contact
            elif contact.id != deal.contact_id:
                deal = None
        if contact is not None:
            project.contact_id = contact.id
            updates.append("contact")
        if deal is not None:
            project.deal_id = deal.id
            updates.append("deal")
        if updates:
            project.save(update_fields=updates)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "9030_contact_purchase_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="zamerproject",
            name="contact",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name="measurement_projects", to="crm.contact"),
        ),
        migrations.AddField(
            model_name="zamerproject",
            name="deal",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name="measurement_projects", to="crm.deal"),
        ),
        migrations.AddField(
            model_name="zamerproject",
            name="revision",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="CalcSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(default="default", max_length=32, unique=True)),
                ("values", models.JSONField(default=apps.crm.models.default_calc_settings)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="calc_settings_updates", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name_plural": "Calculator settings"},
        ),
        migrations.CreateModel(
            name="Estimate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("measurement_snapshot", models.JSONField(default=dict)),
                ("lines", models.JSONField(default=list)),
                ("totals", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("draft", "Чернетка"), ("sent", "Надіслано"),
                                                     ("accepted", "Погоджено"), ("archived", "Архів")],
                                            db_index=True, default="draft", max_length=16)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                              related_name="estimates", to="crm.contact")),
                ("deal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name="estimates", to="crm.deal")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name="estimates", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              related_name="estimates", to="crm.zamerproject")),
            ],
            options={"ordering": ["-updated_at", "-id"]},
        ),
        migrations.AddConstraint(
            model_name="estimate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deal__isnull", False), ("project__isnull", False)),
                fields=("project", "deal"), name="uniq_project_deal_estimate"),
        ),
        migrations.RunPython(link_existing_projects, migrations.RunPython.noop),
    ]
