# Generated by Django 5.0.14 on 2026-08-21 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9041_funnel_is_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=160, unique=True)),
                ('event_name', models.CharField(db_index=True, max_length=64)),
                ('source_type', models.CharField(choices=[('lead', 'Лід'), ('deal', 'Сделка'), ('payment', 'Оплата')], db_index=True, max_length=16)),
                ('source_id', models.PositiveBigIntegerField(db_index=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('processing', 'Відправляється'), ('sent', 'Відправлено'), ('failed', 'Помилка'), ('skipped', 'Пропущено')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_conversion_events', to='crm.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_conversion_events', to='crm.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_conversion_events', to='crm.lead')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_conversion_events', to='crm.payment')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_conversion_events', to='crm.stage')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='crm_meta_status_created')],
            },
        ),
    ]
