from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("crm", "9043_meta_attribution")]

    operations = [
        migrations.CreateModel(
            name="MetaAdDailyStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("level", models.CharField(choices=[("account", "Акаунт"), ("ad", "Оголошення")], db_index=True, max_length=12)),
                ("object_id", models.CharField(db_index=True, max_length=64)),
                ("account_id", models.CharField(db_index=True, max_length=64)),
                ("account_name", models.CharField(blank=True, default="", max_length=255)),
                ("currency", models.CharField(blank=True, default="USD", max_length=8)),
                ("campaign_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("campaign_name", models.CharField(blank=True, default="", max_length=255)),
                ("campaign_objective", models.CharField(blank=True, default="", max_length=80)),
                ("adset_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("adset_name", models.CharField(blank=True, default="", max_length=255)),
                ("ad_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("ad_name", models.CharField(blank=True, default="", max_length=255)),
                ("effective_status", models.CharField(blank=True, default="", max_length=32)),
                ("creative_id", models.CharField(blank=True, default="", max_length=64)),
                ("media_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("thumbnail_url", models.URLField(blank=True, default="", max_length=1200)),
                ("permalink_url", models.URLField(blank=True, default="", max_length=1200)),
                ("spend", models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ("impressions", models.PositiveBigIntegerField(default=0)),
                ("reach", models.PositiveBigIntegerField(default=0)),
                ("clicks", models.PositiveBigIntegerField(default=0)),
                ("outbound_clicks", models.PositiveBigIntegerField(default=0)),
                ("messages_started", models.PositiveBigIntegerField(default=0)),
                ("meta_leads", models.PositiveBigIntegerField(default=0)),
                ("purchases", models.PositiveBigIntegerField(default=0)),
                ("video_views", models.PositiveBigIntegerField(default=0)),
                ("actions", models.JSONField(blank=True, default=dict)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-date", "account_id", "level", "object_id"]},
        ),
        migrations.CreateModel(
            name="MetaContentStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ig_account_id", models.CharField(db_index=True, max_length=64)),
                ("media_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("caption", models.TextField(blank=True, default="")),
                ("media_type", models.CharField(blank=True, default="", max_length=32)),
                ("media_product_type", models.CharField(blank=True, default="", max_length=32)),
                ("permalink", models.URLField(blank=True, default="", max_length=1200)),
                ("thumbnail_url", models.URLField(blank=True, default="", max_length=1200)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("like_count", models.PositiveBigIntegerField(default=0)),
                ("comments_count", models.PositiveBigIntegerField(default=0)),
                ("reach", models.PositiveBigIntegerField(blank=True, null=True)),
                ("views", models.PositiveBigIntegerField(blank=True, null=True)),
                ("saved", models.PositiveBigIntegerField(blank=True, null=True)),
                ("shares", models.PositiveBigIntegerField(blank=True, null=True)),
                ("total_interactions", models.PositiveBigIntegerField(blank=True, null=True)),
                ("follows", models.PositiveBigIntegerField(blank=True, null=True)),
                ("profile_visits", models.PositiveBigIntegerField(blank=True, null=True)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("first_synced_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-published_at", "-id"]},
        ),
        migrations.AddConstraint(
            model_name="metaaddailystat",
            constraint=models.UniqueConstraint(fields=("date", "level", "account_id", "object_id"), name="uniq_meta_ad_daily_object"),
        ),
        migrations.AddIndex(model_name="metaaddailystat", index=models.Index(fields=["level", "date"], name="crm_meta_ad_level_date")),
        migrations.AddIndex(model_name="metaaddailystat", index=models.Index(fields=["campaign_id", "date"], name="crm_meta_ad_campaign_date")),
        migrations.AddIndex(model_name="metaaddailystat", index=models.Index(fields=["adset_id", "date"], name="crm_meta_ad_adset_date")),
        migrations.AddIndex(model_name="metaaddailystat", index=models.Index(fields=["ad_id", "date"], name="crm_meta_ad_ad_date")),
        migrations.AddIndex(model_name="metacontentstat", index=models.Index(fields=["ig_account_id", "published_at"], name="crm_meta_content_pub")),
        migrations.AddIndex(model_name="metacontentstat", index=models.Index(fields=["media_product_type", "published_at"], name="crm_meta_content_type")),
    ]
