# Generated by Codex on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "9048_meta_sync_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaPaidFollowStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("campaign_name", models.CharField(blank=True, default="", max_length=255)),
                ("adset_name", models.CharField(blank=True, default="", max_length=255)),
                ("ad_name", models.CharField(blank=True, default="", max_length=255)),
                ("follows", models.PositiveIntegerField(default=0)),
                ("report_uid", models.CharField(blank=True, default="", max_length=64)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-date", "campaign_name", "adset_name", "ad_name"]},
        ),
        migrations.AddConstraint(
            model_name="metapaidfollowstat",
            constraint=models.UniqueConstraint(
                fields=("date", "campaign_name", "adset_name", "ad_name"),
                name="uniq_meta_paid_follow_daily_ad",
            ),
        ),
        migrations.AddIndex(
            model_name="metapaidfollowstat",
            index=models.Index(fields=["date", "campaign_name"], name="crm_meta_follow_campaign_day"),
        ),
        migrations.AddIndex(
            model_name="metapaidfollowstat",
            index=models.Index(fields=["date", "adset_name"], name="crm_meta_follow_adset_day"),
        ),
        migrations.AddIndex(
            model_name="metapaidfollowstat",
            index=models.Index(fields=["date", "ad_name"], name="crm_meta_follow_ad_day"),
        ),
    ]
