# Generated by Django 5.0.14 on 2026-09-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9065_paylink_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='advance_adjust',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Коригування авансу'),
        ),
        migrations.AlterField(
            model_name='dealroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kbentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kbunknownquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
