# Generated by Django 5.0.14 on 2026-10-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9067_dialogreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogreview',
            name='kind',
            field=models.CharField(default='daily', help_text='daily / weekly', max_length=10),
        ),
    ]
