# Generated by Django 5.0.14 on 2026-06-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_transaction_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelspend',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='findirection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='findirection',
            name='plan_expense',
            field=models.DecimalField(decimal_places=2, default=0, help_text='План витрат', max_digits=14),
        ),
        migrations.AlterField(
            model_name='findirection',
            name='plan_income',
            field=models.DecimalField(decimal_places=2, default=0, help_text='План доходу (рік/період)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='finmodelarticle',
            name='category',
            field=models.CharField(choices=[('revenue_fund', 'Фонди виручки (% з виручки)'), ('payment_fee', 'Комісія еквайрингу (₴/угода)'), ('variable', 'Перемінні витрати (% від маржі)'), ('fixed', 'Постійні витрати (₴/міс)'), ('upr_cat2', "УПР обов'язкові (₴/міс, у ТБ)"), ('upr_cat3', 'УПР відмовні (₴/міс)'), ('warehouse_rate', 'Ставки складу'), ('skd', 'Фонд СКД / розвитку (грн/міс)'), ('config', 'Конфіг / ліміти')], max_length=24),
        ),
        migrations.AlterField(
            model_name='finmodelarticle',
            name='value_type',
            field=models.CharField(choices=[('percent', '%'), ('fixed_sum_per_month', '₴/місяць'), ('fixed_per_deal', '₴/угода'), ('auto_meta_ads', 'Авто Meta-ads')], default='percent', max_length=24),
        ),
    ]
