# Generated by Django 5.0.14 on 2026-07-03 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9001_tx_date_writable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='import_batch',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Партія імпорту (банк/виписка) — для відкату помилкового завантаження', max_length=48),
        ),
        migrations.AlterField(
            model_name='finmodelarticle',
            name='category',
            field=models.CharField(choices=[('revenue_fund', 'Фонди виручки (% з виручки)'), ('payment_fee', 'Комісія еквайрингу (₴/угода)'), ('variable', 'Перемінні витрати (% від маржі)'), ('fixed', 'Постійні витрати (₴/міс)'), ('upr_cat2', "УПР обов'язкові (₴/міс, у ТБ)"), ('upr_cat3', 'УПР відмовні (₴/міс)'), ('warehouse_rate', 'Ставки складу'), ('skd', 'Фонд СКД / розвитку (грн/міс)'), ('config', 'Конфіг / ліміти'), ('salary', 'ЗП менеджера (ставки)')], max_length=24),
        ),
        migrations.AlterField(
            model_name='managerplan',
            name='ambition_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Амбіція (stretch)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='managerplan',
            name='min_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Мінімум (поріг)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='managerplan',
            name='target_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Норма / ціль', max_digits=14),
        ),
        migrations.AlterField(
            model_name='workday',
            name='status',
            field=models.CharField(choices=[('worked', 'Робочий день'), ('overtime', 'Перевиконання (вихід у вихідний)'), ('dayoff', 'Вихідний'), ('sick', 'Лікарняний'), ('vacation', 'Відпустка'), ('absent', 'Прогул')], default='worked', max_length=12),
        ),
        migrations.CreateModel(
            name='BankRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('osnd', 'Призначення платежу'), ('counterparty', 'Контрагент')], default='osnd', max_length=16)),
                ('contains', models.CharField(max_length=160, verbose_name='Містить текст')),
                ('direction', models.CharField(blank=True, default='', help_text='Порожньо = будь-який; in/out', max_length=10)),
                ('set_counterparty', models.CharField(blank=True, default='', max_length=160)),
                ('priority', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('set_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.category')),
                ('set_fin_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.finmodelarticle')),
                ('set_fin_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.findirection')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
    ]
