# Generated by Django 5.0.14 on 2026-07-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9002_alter_transaction_options_transaction_import_batch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='account',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Порядок у списках (менше — вище)'),
        ),
    ]
