# Generated by Django 5.0.14 on 2026-07-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9003_alter_account_options_account_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='op_time',
            field=models.TimeField(blank=True, help_text='Час операції (з банку або момент внесення)', null=True),
        ),
    ]
