# Generated by Django 5.0.14 on 2026-07-04 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9004_transaction_op_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Батьківська категорія (підкатегорії ФінМапа)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.category'),
        ),
    ]
