# Generated by Django 5.0.14 on 2026-07-04 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9020_dealitem_cost_alter_payment_provider'),
        ('finance', '9005_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payable', 'Кредиторка (ми винні)'), ('receivable', 'Дебіторка (нам винні)')], db_index=True, max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField(db_index=True)),
                ('counterparty', models.CharField(blank=True, max_length=160)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Заплановано'), ('paid', 'Оплачено'), ('canceled', 'Скасовано')], db_index=True, default='planned', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_payments', to='finance.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_payments', to='finance.category')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_payments', to='crm.deal')),
                ('paid_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.transaction')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
    ]
