# Generated by Django 5.0.14 on 2026-07-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9006_plannedpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrule',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='{category, fin_direction, fin_article, counterparty, channel}'),
        ),
        migrations.AddField(
            model_name='bankrule',
            name='conditions',
            field=models.JSONField(blank=True, default=list, help_text='[{field: osnd|counterparty|account, op: contains|not_contains|equals, text}]'),
        ),
        migrations.AddField(
            model_name='bankrule',
            name='hits',
            field=models.IntegerField(default=0, help_text='скільки разів правило спрацювало'),
        ),
        migrations.AddField(
            model_name='bankrule',
            name='logic',
            field=models.CharField(default='or', help_text='and | or — як поєднувати умови', max_length=3),
        ),
        migrations.AddField(
            model_name='bankrule',
            name='name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
