# Generated by Django 5.0.14 on 2026-07-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9007_bankrule_actions_bankrule_conditions_bankrule_hits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrule',
            name='contains',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Містить текст'),
        ),
    ]
