# Generated by Django 5.0.14 on 2026-07-05 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9008_alter_bankrule_contains'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedpayment',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='plannedpayment',
            name='fin_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_payments', to='finance.finmodelarticle'),
        ),
        migrations.AddField(
            model_name='plannedpayment',
            name='fin_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_payments', to='finance.findirection'),
        ),
    ]
