# Generated by Django 5.0.14 on 2026-07-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9009_plannedpayment_channel_plannedpayment_fin_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Зараховано на рахунок-одержувач у ЙОГО валюті (переказ з конвертацією, напр. грн→USD); пусто = amount', max_digits=14, null=True),
        ),
    ]
