# Generated by Django 5.0.14 on 2026-07-06 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9010_transaction_transfer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='finmodelarticle',
            name='fin_direction',
            field=models.ForeignKey(blank=True, help_text='Напрямок фонду (порожньо = загальний фонд, ділиться між напрямками по виручці)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_articles', to='finance.findirection'),
        ),
    ]
