# Generated by Django 5.0.14 on 2026-07-06 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9011_finmodelarticle_fin_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fin_article',
            field=models.ForeignKey(blank=True, help_text='Фонд, куди автоматично падає операція цієї категорії', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='finance.finmodelarticle'),
        ),
        migrations.AddField(
            model_name='category',
            name='fin_direction',
            field=models.ForeignKey(blank=True, help_text='Напрямок за замовчуванням для операцій цієї категорії', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='finance.findirection'),
        ),
        migrations.AddField(
            model_name='category',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Не показувати у виборі (дублі/застарілі); історія лишається'),
        ),
    ]
