# Generated by Django 5.0.14 on 2026-07-07 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9020_dealitem_cost_alter_payment_provider'),
        ('finance', '9012_category_fin_article_category_fin_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Клієнт (обʼєкт): усі гроші по клієнту видно в його картці, навіть якщо контрагент — майстер чи магазин', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_transactions', to='crm.contact'),
        ),
    ]
