# Generated by Django 5.0.14 on 2026-07-07 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9020_dealitem_cost_alter_payment_provider'),
        ('finance', '9013_transaction_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedpayment',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Клієнт (обʼєкт), по якому цей борг', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_payments', to='crm.contact'),
        ),
    ]
