# Generated by Django 5.0.14 on 2026-07-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9015_alter_category_options_category_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='in_planning',
            field=models.BooleanField(default=True, help_text='Рахунок бере участь у «До розподілу» (Планування)'),
        ),
    ]
