# Generated by Django 5.0.14 on 2026-07-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9016_account_in_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedpayment',
            name='is_loan',
            field=models.BooleanField(default=False, help_text='Дебіторка-позика: я дав СВОЇ гроші в борг → повернення НЕ прибуток (лише тіло боргу). Торгова дебіторка (від продажу) = False → прибуток.'),
        ),
    ]
