# Generated by Django 5.0.14 on 2026-07-11 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9017_plannedpayment_is_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payer_direction',
            field=models.ForeignKey(blank=True, help_text='Підрозділ, чия каса сплатила — для внутрішнього боргу при спільній витраті між підрозділами (пусто = звичайна операція)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.findirection'),
        ),
        migrations.CreateModel(
            name='TransactionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.category')),
                ('fin_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.findirection')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='finance.transaction')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
