# Generated by Django 5.0.14 on 2026-07-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9023_changelogentry'),
        ('finance', '9018_transaction_payer_direction_transactionsplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='findirection',
            name='internal_contact',
            field=models.ForeignKey(blank=True, help_text='Внутрішній контрагент цього підрозділу (створюється авто при взаєморозрахунках між підрозділами)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='plannedpayment',
            name='counterparty_contact',
            field=models.ForeignKey(blank=True, help_text='Друга сторона внутрішнього боргу (підрозділ-кредитор), щоб борг було видно в обох картках', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='plannedpayment',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False, help_text='Внутрішній борг між підрозділами (не зовнішній контрагент)'),
        ),
        migrations.AddField(
            model_name='plannedpayment',
            name='source_transaction',
            field=models.ForeignKey(blank=True, help_text='Операція-розподіл, що породила цей внутрішній борг', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_debts', to='finance.transaction'),
        ),
    ]
