# Generated by Django 5.0.14 on 2026-07-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9021_plannedpayment_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='pauses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
