# Generated by Django 5.0.14 on 2026-07-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9022_worksession_pauses'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
