# Generated by Django 5.0.14 on 2026-10-01 14:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '9068_alter_dialogreview_kind'),
        ('finance', '9029_managerplan_online_offline'),
        ('warehouse', '0032_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedpayment',
            name='source_stock',
            field=models.ForeignKey(blank=True, help_text='Прихід, що породив цей борг — при правці приходу борг (сума/дата) дзеркалиться, якщо не оплачений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_payments', to='warehouse.stockdocument'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напр. «Позика Риги» або «Кредитний ліміт ФОП»', max_length=160, verbose_name='Назва')),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Тіло на старті')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='У валюті кредиту. Міняється нарахуваннями і платежами', max_digits=14, verbose_name='Поточний залишок')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='Валюта')),
                ('rate_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Ставка, %')),
                ('rate_period', models.CharField(choices=[('month', 'На місяць'), ('day', 'На день'), ('year', 'Річна'), ('none', 'Без відсотків')], default='month', max_length=8, verbose_name='За період')),
                ('capitalize', models.BooleanField(default=True, help_text='Так — наступного разу відсоток рахується від більшої суми', verbose_name='Відсотки додаються до тіла')),
                ('accrual_day', models.PositiveSmallIntegerField(default=1, help_text='Для місячної ставки: 24 = 24-го числа. Для денної не використовується', verbose_name='День нарахування')),
                ('started_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Початок обліку')),
                ('last_accrual', models.DateField(blank=True, null=True, verbose_name='Останнє нарахування')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creditor', models.ForeignKey(blank=True, help_text='Хто дав гроші (контрагент типу «Кредитор»)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_given', to='crm.contact')),
                ('planned_payment', models.ForeignKey(blank=True, help_text='Дзеркало в Дт/Кт — сума оновлюється автоматично', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.plannedpayment')),
            ],
            options={
                'verbose_name': 'Кредит / позика',
                'verbose_name_plural': 'Кредити і позики',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LoanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('accrual', 'Нарахування відсотків'), ('payment', 'Платіж'), ('draw', 'Довзяли'), ('adjust', 'Коригування')], db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сума у валюті кредиту')),
                ('rate_uah', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='Курс до гривні')),
                ('amount_uah', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сума у гривні')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Залишок після')),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.loan')),
                ('transaction', models.ForeignKey(blank=True, help_text='Операція в журналі, якщо платіж пройшов через касу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Рух по кредиту',
                'verbose_name_plural': 'Рухи по кредитах',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
