# Generated by Django 5.0.14 on 2026-10-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9030_alter_plannedpayment_source_stock_loan_loanentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanentry',
            name='kind',
            field=models.CharField(choices=[('accrual', 'Нарахування відсотків'), ('payment', 'Платіж'), ('interest', 'Сплата відсотків'), ('draw', 'Довзяли'), ('adjust', 'Коригування')], db_index=True, max_length=10),
        ),
    ]
