# Generated by Django 5.0.14 on 2026-10-01 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '9031_alter_loanentry_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Рахунок, на якому живе цей кредит — щоб платежі підтягувались саме сюди, а не до всіх кредитів того самого банку', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='finance.account'),
        ),
        migrations.AddField(
            model_name='loan',
            name='pull_from',
            field=models.DateField(blank=True, help_text='Операції до цієї дати вже внесені вручну — не дублювати', null=True, verbose_name='Підтягувати з дати'),
        ),
    ]
