# Generated by Django 5.0.14 on 2026-09-14 14:10

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "9061_lead_quality"),
        ("warehouse", "0022_product_consumption"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('threshold_uah', models.DecimalField(decimal_places=2, default=0, help_text='Поріг оплаченого обороту, ₴. Старт = 0', max_digits=14)),
                ('margin_share', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Частка маржі для ПІДКАЗКИ знижки за правилом ATM (0.25 = 25% маржі)', max_digits=4)),
                ('color', models.CharField(default='#be185d', max_length=9)),
                ('is_active', models.BooleanField(default=True, help_text='Вимкнений рівень не присвоюється (видаляти не можна)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рівень партнера',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerDiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('excluded', models.BooleanField(default=False, help_text='Товар без партнерської знижки (жорсткий 0)')),
                ('suggested_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Що пропонувало правило ATM у момент збереження', max_digits=5, null=True)),
                ('below_min_reason', models.CharField(blank=True, default='', help_text='Виняток товару нижче мінімальної маржі: причина (право partners.below_min)', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='warehouse.productcategory')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='warehouse.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='partners.partnerlevel')),
            ],
            options={
                'verbose_name': 'Партнерська знижка',
            },
        ),
        migrations.CreateModel(
            name='PartnerRuleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id_ref', models.IntegerField(blank=True, null=True)),
                ('level_name', models.CharField(blank=True, default='', max_length=40)),
                ('category_id_ref', models.IntegerField(blank=True, null=True)),
                ('product_id_ref', models.IntegerField(blank=True, null=True)),
                ('target_name', models.CharField(blank=True, default='', max_length=255)),
                ('old_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('old_excluded', models.BooleanField(blank=True, null=True)),
                ('new_excluded', models.BooleanField(blank=True, null=True)),
                ('source', models.CharField(default='manual', help_text='manual / atm / seed', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_margin_pp', models.DecimalField(decimal_places=2, default=Decimal('15'), help_text='Скільки п.п. маржі (від роздрібної ціни) має лишитись після знижки', max_digits=5)),
                ('round_step', models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Підказку округлюємо ВНИЗ до цього кроку, %', max_digits=5)),
                ('turnover_from', models.DateField(default=datetime.date(2026, 5, 5), help_text='Оборот рахуємо з цієї дати')),
                ('exclude_funnel_ids', models.JSONField(blank=True, default=list, help_text='Воронки, оплати яких не йдуть в оборот (тести)')),
                ('exclude_in_category_ids', models.JSONField(blank=True, default=list, help_text='Категорії надходжень, що НЕ виручка (повернення від постачальника тощо)')),
                ('refund_category_ids', models.JSONField(blank=True, default=list, help_text='Категорії витрат-повернень клієнту — віднімаються з обороту')),
                ('no_discount_category_ids', models.JSONField(blank=True, default=list, help_text='Категорії без партнерської знижки взагалі (тест-набори)')),
                ('start_fixed', models.JSONField(blank=True, default=dict, help_text='Затверджені Олегом знижки рівня «Старт» на кореневі категорії {category_id: %}')),
                ('auto_raise', models.BooleanField(default=True, help_text='Підвищувати рівень одразу після оплати')),
                ('auto_apply', models.BooleanField(default=False, help_text='Крок 5 (пізніше): автознижка в угодах. ВИМКНЕНО')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Налаштування партнерської програми',
            },
        ),
        migrations.CreateModel(
            name='PartnerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Галочка «Партнер» у картці клієнта')),
                ('since', models.DateField(default=datetime.date.today)),
                ('level_at', models.DateTimeField(blank=True, null=True)),
                ('turnover_uah', models.DecimalField(decimal_places=2, default=0, help_text='Кеш обороту', max_digits=14)),
                ('turnover_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_status', to='crm.contact')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='partners.partnerlevel')),
            ],
            options={
                'verbose_name': 'Статус партнера',
            },
        ),
        migrations.CreateModel(
            name='PartnerStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('assign', 'Відмічено партнером'), ('auto_raise', 'Автопідвищення за оборотом'), ('manual', 'Підвищено вручну'), ('unmark', 'Галочку знято'), ('remark', 'Галочку повернуто')], max_length=16)),
                ('turnover_uah', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_history', to='crm.contact')),
                ('new_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='partners.partnerlevel')),
                ('old_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='partners.partnerlevel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='partnerdiscountrule',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('category__isnull', False), ('product__isnull', True)), models.Q(('category__isnull', True), ('product__isnull', False)), _connector='OR'), name='partners_rule_one_target'),
        ),
        migrations.AddConstraint(
            model_name='partnerdiscountrule',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', True)), fields=('level', 'category'), name='partners_rule_uniq_cat'),
        ),
        migrations.AddConstraint(
            model_name='partnerdiscountrule',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('level', 'product'), name='partners_rule_uniq_prod'),
        ),
        migrations.AddConstraint(
            model_name='partnerdiscountrule',
            constraint=models.CheckConstraint(check=models.Q(('pct__gte', 0), ('pct__lte', 100)), name='partners_rule_pct_range'),
        ),
    ]
