# Generated by Django 5.0.14 on 2026-09-15 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='xpevent',
            name='archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Старі правила (до 16.09.2026) — не рахується, лишається для історії'),
        ),
        migrations.AlterField(
            model_name='badgeaward',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='managerlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='xpevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='GamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_sampling', models.BooleanField(default=False, help_text='Раз на тиждень ІІ розбирає випадкову вибірку чатів кожного менеджера (коштує грошей)')),
                ('chat_sample_per_week', models.PositiveSmallIntegerField(default=3, help_text='Скільки чатів одного менеджера за тиждень')),
                ('contests', models.JSONField(blank=True, default=dict, help_text='Змагання тижня: {код: {offer_id, enabled}} — заводить команда rozvytok_contests_seed')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('key', models.CharField(max_length=60)),
                ('text', models.CharField(blank=True, default='', max_length=300)),
                ('done', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'week', 'key')},
            },
        ),
    ]
