# Generated by Django 5.0.14 on 2026-09-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_rozvytok_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamsettings',
            name='chat_sampling',
            field=models.BooleanField(default=False, help_text='Раз на тиждень ШІ розбирає випадкову вибірку чатів кожного менеджера (коштує грошей)'),
        ),
    ]
